import type { Metadata } from "next";
import { notFound } from "next/navigation";
import Image from "next/image";
import Link from "next/link";
import {
  MapPin,
  Clock,
  Car,
  DollarSign,
  Star,
  CheckCircle,
  ArrowRight,
  Phone,
  MessageCircle,
  ChevronDown,
  Navigation,
  TrainFront,
  Landmark,
  BadgeCheck,
} from "lucide-react";
import { Card, CardContent } from "@/components/ui/card";
import { Button } from "@/components/ui/button";
import { Badge } from "@/components/ui/badge";
import Breadcrumb from "@/components/sections/breadcrumb";
import SchemaScript from "@/components/sections/schema-script";
import {
  localBusinessSchema,
  faqSchema,
  breadcrumbSchema,
} from "@/lib/schema";
import { LOCATIONS, getLocationBySlug } from "@/data/locations";
import { TESTIMONIALS } from "@/data/testimonials";
import { FAQS } from "@/data/faqs";
import { BUSINESS, formatWhatsAppHref, formatPhoneHref } from "@/lib/utils";

export const revalidate = 86400;

export async function generateStaticParams() {
  return LOCATIONS.map((l) => ({ slug: l.slug }));
}

// ─── Per-emirate pricing ─────────────────────────────────────────────────────

type Emirate = "dubai" | "abu-dhabi" | "sharjah" | "ajman";

const emirateNormalPrice: Record<Emirate, number> = {
  dubai:       200,
  "abu-dhabi": 200,
  sharjah:     280,
  ajman:       300,
};

const emirateAirportPrice: Record<Emirate, number> = {
  dubai:       250,
  "abu-dhabi": 250,
  sharjah:     300,
  ajman:       320,
};

const emirateNormalPriceDisplay: Record<Emirate, string> = {
  dubai:       "AED 200",
  "abu-dhabi": "From AED 100 sharing",
  sharjah:     "AED 130 sharing",
  ajman:       "AED 130 sharing",
};

// Route label shown in hero / pills
const emirateRouteLabel: Record<Emirate, string> = {
  dubai:       "Dubai ↔ Abu Dhabi",
  "abu-dhabi": "Abu Dhabi ↔ All Emirates",
  sharjah:     "Sharjah ↔ Abu Dhabi",
  ajman:       "Ajman ↔ Abu Dhabi",
};

export async function generateMetadata({
  params,
}: {
  params: Promise<{ slug: string }>;
}): Promise<Metadata> {
  const { slug } = await params;
  const location = getLocationBySlug(slug);
  if (!location) return {};
  const tripPrice = emirateNormalPriceDisplay[location.emirate as Emirate];
  return {
    title: `Car Lift ${location.name} – ${emirateRouteLabel[location.emirate as Emirate]} | Car Lift UAE`,
    description:
      location.description +
      ` Per-trip pricing from ${tripPrice}. GPS tracked, verified drivers.`,
    keywords: location.keywords.join(", "),
    alternates: {
      canonical: `https://www.carliftuae.com/locations/${location.slug}`,
    },
    openGraph: {
      title: `Car Lift ${location.name} – ${tripPrice}/trip`,
      description: location.description,
      // OG image generated by src/app/locations/[slug]/opengraph-image.tsx
    },
  };
}

// ─── What makes this route great ────────────────────────────────────────────

const ROUTE_BENEFITS = [
  "Fixed per-trip pricing — no surprises",
  "Fixed pickup point — just show up on time",
  "Verified, background-checked drivers every day",
  "Real-time GPS tracking on all vehicles",
  "Air-conditioned, well-maintained vehicles",
  "Morning and evening service, 6 days a week",
  "WhatsApp booking — no app required",
  "Airport transfers available on all routes",
];

// ─── Generic FAQs (3 from master list) ──────────────────────────────────────

const GENERIC_FAQS = FAQS.filter((f) =>
  ["Safety", "Booking", "General"].includes(f.category)
).slice(0, 3);

// ─── Emirate badge styles ────────────────────────────────────────────────────

const emirateBadgeClass: Record<Emirate, string> = {
  "abu-dhabi": "bg-amber-100 text-amber-700",
  sharjah:     "bg-blue-100 text-blue-700",
  dubai:       "bg-emerald-100 text-emerald-700",
  ajman:       "bg-purple-100 text-purple-700",
};

const emirateLabel: Record<Emirate, string> = {
  "abu-dhabi": "Abu Dhabi",
  sharjah:     "Sharjah",
  dubai:       "Dubai",
  ajman:       "Ajman",
};

const emirateHeroImage: Record<Emirate, { src: string; alt: string }> = {
  "abu-dhabi": {
    src: "/images/locations/sharjah/sharjah-car-lift-morning-pickup.webp",
    alt: "Abu Dhabi car lift service – inter-emirate rides to Dubai, Sharjah and Ajman",
  },
  sharjah: {
    src: "/images/locations/sharjah/sharjah-car-lift-morning-pickup.webp",
    alt: "Morning car lift pickup in Sharjah – daily commuters heading to Abu Dhabi",
  },
  dubai: {
    src: "/images/locations/business-bay/business-bay-car-lift-professionals.webp",
    alt: "Dubai car lift service – comfortable rides between Dubai and Abu Dhabi",
  },
  ajman: {
    src: "/images/locations/sharjah/sharjah-car-lift-morning-pickup.webp",
    alt: "Daily car lift pickup service in Ajman – shared rides to Abu Dhabi",
  },
};

// ─── Page ───────────────────────────────────────────────────────────────────

export default async function LocationPage({
  params,
}: {
  params: Promise<{ slug: string }>;
}) {
  const { slug } = await params;
  const location = getLocationBySlug(slug);

  if (!location) {
    notFound();
  }

  const emirate = location.emirate as Emirate;
  const normalPrice   = emirateNormalPrice[emirate];
  const airportPrice  = emirateAirportPrice[emirate];
  const priceDisplay  = emirateNormalPriceDisplay[emirate];
  const routeLabel    = emirateRouteLabel[emirate];

  // 4 related locations from same emirate, excluding current
  const relatedLocations = LOCATIONS.filter(
    (l) => l.emirate === location.emirate && l.slug !== slug
  ).slice(0, 4);

  // 3 testimonials — pick evenly spaced for variety
  const testimonials = [
    TESTIMONIALS[0],
    TESTIMONIALS[2],
    TESTIMONIALS[5],
  ].filter(Boolean);

  // WhatsApp with pre-filled message
  const whatsappHref = formatWhatsAppHref(
    BUSINESS.whatsapp,
    `Hi, I need car lift from ${location.name} (${routeLabel})`
  );

  const phoneHref = formatPhoneHref(BUSINESS.phone);

  // All FAQs for schema: location-specific + generic
  const allFaqs = [
    ...location.faqs,
    ...GENERIC_FAQS.map((f) => ({ question: f.question, answer: f.answer })),
  ];

  // Structured data schemas
  const schemas = [
    localBusinessSchema({
      name: `${BUSINESS.name} – ${location.name}`,
      description: location.description,
      geo: {
        "@type": "GeoCoordinates",
        latitude: location.coordinates.lat,
        longitude: location.coordinates.lng,
      },
    }),
    faqSchema(allFaqs),
    breadcrumbSchema([
      { name: "Home",      url: "/" },
      { name: "Locations", url: "/locations" },
      { name: location.name, url: `/locations/${slug}` },
    ]),
  ];

  return (
    <>
      <SchemaScript schema={schemas} />

      {/* ═══════════════════════════════════════════════════════════════════
          1. HERO SECTION
      ════════════════════════════════════════════════════════════════════ */}
      <section
        aria-labelledby="location-hero-heading"
        className="relative overflow-hidden py-16 sm:py-20"
        style={{
          background:
            "linear-gradient(135deg, #0f172a 0%, #1e3a5f 50%, #0c2340 100%)",
        }}
      >
        {/* Location hero image */}
        <Image
          src={emirateHeroImage[emirate].src}
          alt={emirateHeroImage[emirate].alt}
          fill
          priority
          quality={78}
          sizes="100vw"
          className="object-cover opacity-[0.15] select-none pointer-events-none"
        />

        {/* Dot grid */}
        <div
          className="absolute inset-0 opacity-[0.04] pointer-events-none"
          style={{
            backgroundImage:
              "radial-gradient(circle, rgba(255,255,255,0.8) 1px, transparent 1px)",
            backgroundSize: "28px 28px",
          }}
          aria-hidden="true"
        />

        <div className="relative z-10 max-w-5xl mx-auto px-4 sm:px-6 lg:px-8">
          {/* Breadcrumb */}
          <Breadcrumb
            items={[
              { label: "Home",      href: "/" },
              { label: "Locations", href: "/locations" },
              { label: location.name },
            ]}
            className="mb-6 [&_*]:text-slate-400 [&_a]:text-slate-300 [&_a:hover]:text-white"
          />

          <div className="flex flex-col lg:flex-row lg:items-start lg:justify-between gap-10">
            {/* Left: heading + stats + CTAs */}
            <div className="flex-1">
              {/* Emirate badge */}
              <span
                className={`inline-block text-xs font-bold px-3 py-1 rounded-full mb-4 ${emirateBadgeClass[emirate]}`}
              >
                {emirateLabel[emirate]}
              </span>

              <h1
                id="location-hero-heading"
                className="text-3xl sm:text-4xl lg:text-5xl font-extrabold text-white tracking-tight leading-tight mb-4"
              >
                Car Lift {location.name} – {routeLabel}
              </h1>

              <p className="text-slate-300 text-base sm:text-lg leading-relaxed mb-6 max-w-xl">
                {location.description}
              </p>

              {/* Route pill */}
              <div className="inline-flex items-center gap-2 bg-white/10 border border-white/20 rounded-full px-4 py-2 text-sm text-white font-medium mb-6">
                <Navigation className="h-4 w-4 text-blue-400" aria-hidden="true" />
                {routeLabel}
              </div>

              {/* Key stats row */}
              <ul
                className="grid grid-cols-2 sm:grid-cols-4 gap-3 mb-8"
                role="list"
                aria-label="Route key statistics"
              >
                <li className="bg-white/10 border border-white/15 rounded-xl p-4 text-center">
                  <MapPin className="h-5 w-5 text-blue-400 mx-auto mb-1.5" aria-hidden="true" />
                  <p className="text-white font-extrabold text-lg leading-none">
                    {location.distance}
                  </p>
                  <p className="text-slate-400 text-xs mt-1">Distance</p>
                </li>
                <li className="bg-white/10 border border-white/15 rounded-xl p-4 text-center">
                  <Clock className="h-5 w-5 text-blue-400 mx-auto mb-1.5" aria-hidden="true" />
                  <p className="text-white font-extrabold text-lg leading-none">
                    {location.drivingTime}
                  </p>
                  <p className="text-slate-400 text-xs mt-1">Drive Time</p>
                </li>
                <li className="bg-emerald-500/20 border border-emerald-400/30 rounded-xl p-4 text-center">
                  <DollarSign className="h-5 w-5 text-emerald-400 mx-auto mb-1.5" aria-hidden="true" />
                  <p className="text-emerald-300 font-extrabold text-lg leading-none">
                    {priceDisplay}
                  </p>
                  <p className="text-emerald-400/70 text-xs mt-1">/trip</p>
                </li>
                <li className="bg-white/10 border border-white/15 rounded-xl p-4 text-center">
                  <Car className="h-5 w-5 text-blue-400 mx-auto mb-1.5" aria-hidden="true" />
                  <p className="text-white font-extrabold text-lg leading-none">
                    {location.pickupPoints.length}
                  </p>
                  <p className="text-slate-400 text-xs mt-1">Pickup Points</p>
                </li>
              </ul>

              {/* CTAs */}
              <div className="flex flex-col sm:flex-row gap-3">
                <Button asChild variant="whatsapp" size="lg">
                  <a
                    href={whatsappHref}
                    target="_blank"
                    rel="noopener noreferrer"
                    aria-label={`Book car lift from ${location.name} via WhatsApp`}
                  >
                    <MessageCircle className="h-5 w-5" aria-hidden="true" />
                    Book Car Lift from {location.name}
                  </a>
                </Button>
                <Button
                  asChild
                  size="lg"
                  className="border-2 border-white/30 bg-white/10 text-white hover:bg-white/20"
                >
                  <a
                    href={phoneHref}
                    aria-label={`Call ${BUSINESS.name}`}
                  >
                    <Phone className="h-5 w-5" aria-hidden="true" />
                    Call Now
                  </a>
                </Button>
              </div>
            </div>

            {/* Right: what's included card */}
            <aside
              className="lg:w-72 bg-white/10 border border-white/15 backdrop-blur-sm rounded-2xl p-6 shrink-0"
              aria-label="What's included"
            >
              <p className="text-white font-bold text-base mb-4 flex items-center gap-2">
                <CheckCircle className="h-5 w-5 text-emerald-400" aria-hidden="true" />
                What&apos;s Included
              </p>
              <ul className="space-y-3" role="list">
                {[
                  "Morning & evening rides",
                  "GPS-tracked vehicle",
                  "Verified UAE driver",
                  "Air-conditioned vehicle",
                  "Airport transfers available",
                  "WhatsApp support",
                ].map((item) => (
                  <li key={item} className="flex items-center gap-2.5">
                    <CheckCircle
                      className="h-4 w-4 text-emerald-400 shrink-0"
                      aria-hidden="true"
                    />
                    <span className="text-slate-300 text-sm">{item}</span>
                  </li>
                ))}
              </ul>
            </aside>
          </div>
        </div>
      </section>

      {/* ═══════════════════════════════════════════════════════════════════
          2. ABOUT THIS ROUTE
      ════════════════════════════════════════════════════════════════════ */}
      <section
        aria-labelledby="about-route-heading"
        className="py-16 sm:py-20 bg-white"
      >
        <div className="max-w-5xl mx-auto px-4 sm:px-6 lg:px-8">
          <div className="grid grid-cols-1 lg:grid-cols-2 gap-12 items-start">
            {/* Description */}
            <div>
              <p className="text-blue-600 font-semibold text-sm uppercase tracking-widest mb-3">
                About This Route
              </p>
              <h2
                id="about-route-heading"
                className="text-2xl sm:text-3xl font-extrabold text-slate-900 tracking-tight mb-5"
              >
                Car Lift Service from {location.name}
              </h2>
              <p className="text-slate-600 leading-relaxed text-base mb-6">
                {location.longDescription}
              </p>

              {/* What makes it great */}
              <h3 className="text-lg font-bold text-slate-900 mb-4">
                Why Professionals Choose This Route
              </h3>
              <ul className="space-y-2.5" role="list">
                {ROUTE_BENEFITS.map((benefit) => (
                  <li key={benefit} className="flex items-start gap-3">
                    <CheckCircle
                      className="h-4 w-4 text-emerald-500 shrink-0 mt-0.5"
                      aria-hidden="true"
                    />
                    <span className="text-slate-700 text-sm">{benefit}</span>
                  </li>
                ))}
              </ul>
            </div>

            {/* Route details card */}
            <div>
              <Card className="border-slate-200 shadow-sm">
                <CardContent className="p-6 pt-6">
                  <h3 className="font-bold text-slate-900 text-lg mb-5">
                    Route Details
                  </h3>
                  <dl className="space-y-4">
                    {[
                      { label: "Route",          value: routeLabel,                                  icon: Navigation },
                      { label: "Distance",       value: location.distance,                           icon: MapPin     },
                      { label: "Drive Time",     value: location.drivingTime,                        icon: Clock      },
                      { label: "Normal Ride",    value: `AED ${normalPrice}/trip`,                   icon: DollarSign },
                      { label: "Airport Transfer", value: `AED ${airportPrice}/trip`,                icon: DollarSign },
                    ].map(({ label, value, icon: Icon }) => (
                      <div
                        key={label}
                        className="flex items-center justify-between py-2.5 border-b border-slate-100 last:border-0"
                      >
                        <dt className="flex items-center gap-2 text-sm text-slate-500">
                          <Icon className="h-4 w-4 text-slate-400" aria-hidden="true" />
                          {label}
                        </dt>
                        <dd className="text-sm font-semibold text-slate-900">
                          {value}
                        </dd>
                      </div>
                    ))}
                  </dl>

                  {/* Morning timing note */}
                  <div className="mt-5 rounded-xl bg-blue-50 border border-blue-100 p-4">
                    <p className="text-blue-800 text-xs font-semibold mb-1">
                      Departure Times (Morning)
                    </p>
                    <p className="text-blue-700 text-xs leading-relaxed">
                      6:30 AM · 7:00 AM · 7:30 AM · 8:00 AM
                      <br />
                      <span className="text-blue-500">
                        Evening return: 5:00 PM · 5:30 PM · 6:00 PM · 6:30 PM
                      </span>
                    </p>
                  </div>
                </CardContent>
              </Card>

              {/* Cost comparison callout */}
              <div className="mt-4 rounded-xl bg-emerald-50 border border-emerald-200 p-5 flex items-start gap-4">
                <div className="w-10 h-10 rounded-full bg-emerald-500 flex items-center justify-center shrink-0">
                  <DollarSign className="h-5 w-5 text-white" aria-hidden="true" />
                </div>
                <div>
                  <p className="font-bold text-emerald-900 text-sm mb-1">
                    Cost-Effective Inter-Emirate Travel
                  </p>
                  <p className="text-emerald-700 text-xs leading-relaxed">
                    Driving yourself from {location.name} means fuel, tolls, and
                    parking costs. Our car lift offers a fixed, affordable rate
                    of {priceDisplay}/trip with no hidden charges.
                  </p>
                </div>
              </div>
            </div>
          </div>
        </div>
      </section>

      {/* ═══════════════════════════════════════════════════════════════════
          3. PICKUP POINTS
      ════════════════════════════════════════════════════════════════════ */}
      <section
        aria-labelledby="pickup-points-heading"
        className="py-16 sm:py-20 bg-slate-50"
      >
        <div className="max-w-5xl mx-auto px-4 sm:px-6 lg:px-8">
          <div className="text-center mb-10">
            <p className="text-blue-600 font-semibold text-sm uppercase tracking-widest mb-3">
              Where We Pick You Up
            </p>
            <h2
              id="pickup-points-heading"
              className="text-2xl sm:text-3xl font-extrabold text-slate-900 tracking-tight mb-4"
            >
              Pickup Points in {location.name}
            </h2>
            <p className="text-slate-600 max-w-xl mx-auto text-sm leading-relaxed">
              We currently operate from the points below. Tell us your building
              name and we&apos;ll confirm the exact meeting spot.
            </p>
          </div>

          <ul
            className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 gap-4 list-none mb-8"
            role="list"
          >
            {location.pickupPoints.map((point) => (
              <li
                key={point}
                className="flex items-center gap-3 bg-white border border-slate-200 rounded-xl px-4 py-3.5 shadow-sm"
              >
                <MapPin
                  className="h-5 w-5 text-blue-500 shrink-0"
                  aria-hidden="true"
                />
                <span className="text-slate-800 font-medium text-sm">
                  {point}
                </span>
              </li>
            ))}
          </ul>

          <p className="text-center text-slate-500 text-xs italic">
            Don&apos;t see your area? WhatsApp us — we&apos;ll add your
            location or suggest the closest pickup point.
          </p>

          <div className="flex justify-center mt-6">
            <Button asChild variant="whatsapp" size="default">
              <a
                href={whatsappHref}
                target="_blank"
                rel="noopener noreferrer"
                aria-label={`Ask about pickup points in ${location.name} via WhatsApp`}
              >
                <MessageCircle className="h-4 w-4" aria-hidden="true" />
                Confirm My Pickup Point
              </a>
            </Button>
          </div>
        </div>
      </section>

      {/* ═══════════════════════════════════════════════════════════════════
          4. LANDMARKS & ORIENTATION
      ════════════════════════════════════════════════════════════════════ */}
      <section
        aria-labelledby="landmarks-heading"
        className="py-16 sm:py-20 bg-white"
      >
        <div className="max-w-5xl mx-auto px-4 sm:px-6 lg:px-8">
          <div className="grid grid-cols-1 lg:grid-cols-2 gap-12">
            {/* Landmarks */}
            <div>
              <div className="flex items-center gap-3 mb-5">
                <div className="w-9 h-9 rounded-xl bg-blue-600 flex items-center justify-center shrink-0">
                  <Landmark className="h-5 w-5 text-white" aria-hidden="true" />
                </div>
                <h2
                  id="landmarks-heading"
                  className="text-xl font-extrabold text-slate-900"
                >
                  Nearby Landmarks
                </h2>
              </div>
              {location.landmarks.length > 0 ? (
                <ul className="space-y-2.5" role="list">
                  {location.landmarks.map((landmark) => (
                    <li
                      key={landmark}
                      className="flex items-center gap-3 p-3 rounded-xl bg-slate-50 border border-slate-100"
                    >
                      <MapPin
                        className="h-4 w-4 text-blue-500 shrink-0"
                        aria-hidden="true"
                      />
                      <span className="text-slate-700 text-sm font-medium">
                        {landmark}
                      </span>
                    </li>
                  ))}
                </ul>
              ) : (
                <p className="text-slate-500 text-sm">
                  Contact us to confirm nearby pickup landmarks.
                </p>
              )}
            </div>

            {/* Metro stations */}
            <div>
              <div className="flex items-center gap-3 mb-5">
                <div className="w-9 h-9 rounded-xl bg-slate-800 flex items-center justify-center shrink-0">
                  <TrainFront className="h-5 w-5 text-white" aria-hidden="true" />
                </div>
                <h2 className="text-xl font-extrabold text-slate-900">
                  Nearby Metro Stations
                </h2>
              </div>
              {location.nearbyMetro.length > 0 ? (
                <ul className="space-y-2.5 mb-6" role="list">
                  {location.nearbyMetro.map((metro) => (
                    <li
                      key={metro}
                      className="flex items-center gap-3 p-3 rounded-xl bg-slate-50 border border-slate-100"
                    >
                      <TrainFront
                        className="h-4 w-4 text-slate-500 shrink-0"
                        aria-hidden="true"
                      />
                      <span className="text-slate-700 text-sm font-medium">
                        {metro}
                      </span>
                    </li>
                  ))}
                </ul>
              ) : (
                <div className="p-4 rounded-xl bg-amber-50 border border-amber-100 mb-6">
                  <p className="text-amber-800 text-sm">
                    No metro station is directly nearby — our car lift is an
                    ideal door-to-door alternative for inter-emirate travel.
                  </p>
                </div>
              )}

              {/* Mini orientation note */}
              <div className="rounded-xl bg-blue-50 border border-blue-100 p-4">
                <p className="text-blue-800 text-sm font-semibold mb-1">
                  Door-to-Door Service
                </p>
                <p className="text-blue-700 text-xs leading-relaxed">
                  Our car lift picks you up near your home in {location.name}{" "}
                  and drops you at your destination — no transfers needed.
                </p>
              </div>
            </div>
          </div>
        </div>
      </section>

      {/* ═══════════════════════════════════════════════════════════════════
          5. PRICING
      ════════════════════════════════════════════════════════════════════ */}
      <section
        aria-labelledby="pricing-heading"
        className="py-16 sm:py-20 bg-slate-50"
      >
        <div className="max-w-5xl mx-auto px-4 sm:px-6 lg:px-8">
          <div className="text-center mb-10">
            <p className="text-blue-600 font-semibold text-sm uppercase tracking-widest mb-3">
              Transparent Pricing
            </p>
            <h2
              id="pricing-heading"
              className="text-2xl sm:text-3xl font-extrabold text-slate-900 tracking-tight mb-4"
            >
              Car Lift {location.name} – Pricing
            </h2>
            <p className="text-slate-600 max-w-xl mx-auto text-sm leading-relaxed">
              Fixed per-trip rates. No hidden charges. Book via WhatsApp in minutes.
            </p>
          </div>

          <div className="grid grid-cols-1 sm:grid-cols-2 gap-5 mb-10 max-w-2xl mx-auto">
            {/* Normal/shared ride */}
            <Card className="border-2 border-blue-600 shadow-md relative">
              <div className="absolute -top-3 left-1/2 -translate-x-1/2">
                <Badge variant="default" className="text-xs px-3">
                  Most Popular
                </Badge>
              </div>
              <CardContent className="p-6 pt-7 text-center">
                <p className="text-slate-500 text-xs font-semibold uppercase tracking-wide mb-2">
                  Normal / Shared Ride
                </p>
                <p className="text-4xl font-extrabold text-slate-900 mb-1">
                  AED {normalPrice}
                </p>
                <p className="text-slate-500 text-xs mb-5">/trip</p>
                <ul className="space-y-2 text-left mb-6" role="list">
                  {[
                    "Per trip — no commitment",
                    "3–4 passengers shared",
                    "Fixed pickup point",
                    "Book via WhatsApp",
                  ].map((f) => (
                    <li key={f} className="flex items-center gap-2 text-sm text-slate-700">
                      <CheckCircle className="h-4 w-4 text-emerald-500 shrink-0" aria-hidden="true" />
                      {f}
                    </li>
                  ))}
                </ul>
                <Button asChild variant="default" size="default" className="w-full">
                  <a
                    href={whatsappHref}
                    target="_blank"
                    rel="noopener noreferrer"
                  >
                    <MessageCircle className="h-4 w-4" aria-hidden="true" />
                    Book Now
                  </a>
                </Button>
              </CardContent>
            </Card>

            {/* Airport transfer */}
            <Card className="border-slate-200">
              <CardContent className="p-6 pt-6 text-center">
                <p className="text-slate-500 text-xs font-semibold uppercase tracking-wide mb-2">
                  Airport Transfer
                </p>
                <p className="text-4xl font-extrabold text-slate-900 mb-1">
                  AED {airportPrice}
                </p>
                <p className="text-slate-500 text-xs mb-5">/trip</p>
                <ul className="space-y-2 text-left mb-6" role="list">
                  {[
                    "Airport pick-up or drop-off",
                    "Flight tracking included",
                    "Fixed rate — no surcharges",
                    "Book via WhatsApp",
                  ].map((f) => (
                    <li key={f} className="flex items-center gap-2 text-sm text-slate-700">
                      <CheckCircle className="h-4 w-4 text-emerald-500 shrink-0" aria-hidden="true" />
                      {f}
                    </li>
                  ))}
                </ul>
                <Button asChild variant="outline" size="default" className="w-full">
                  <a
                    href={formatWhatsAppHref(
                      BUSINESS.whatsapp,
                      `Hi, I'd like to book an airport transfer from/to ${location.name}.`
                    )}
                    target="_blank"
                    rel="noopener noreferrer"
                  >
                    Book Airport Transfer
                  </a>
                </Button>
              </CardContent>
            </Card>
          </div>

          <div className="text-center">
            <p className="text-slate-500 text-sm mb-4">
              Need a custom quote or private vehicle?
            </p>
            <Button asChild variant="outline" size="default">
              <Link href="/pricing">
                View Full Pricing Page
                <ArrowRight className="h-4 w-4" aria-hidden="true" />
              </Link>
            </Button>
          </div>
        </div>
      </section>

      {/* ═══════════════════════════════════════════════════════════════════
          6. FAQ SECTION
      ════════════════════════════════════════════════════════════════════ */}
      <section
        aria-labelledby="faq-heading"
        className="py-16 sm:py-20 bg-white"
      >
        <div className="max-w-3xl mx-auto px-4 sm:px-6 lg:px-8">
          <div className="text-center mb-10">
            <p className="text-blue-600 font-semibold text-sm uppercase tracking-widest mb-3">
              Common Questions
            </p>
            <h2
              id="faq-heading"
              className="text-2xl sm:text-3xl font-extrabold text-slate-900 tracking-tight mb-4"
            >
              Frequently Asked Questions – Car Lift from {location.name}
            </h2>
          </div>

          <dl className="space-y-4">
            {/* Location-specific FAQs */}
            {location.faqs.map((faq, index) => (
              <details
                key={`loc-${index}`}
                className="group border border-slate-200 rounded-2xl overflow-hidden"
              >
                <summary className="flex items-center justify-between gap-4 cursor-pointer p-5 sm:p-6 font-semibold text-slate-900 hover:bg-slate-50 transition-colors list-none [&::-webkit-details-marker]:hidden">
                  <dt className="text-left text-base">{faq.question}</dt>
                  <ChevronDown
                    className="h-5 w-5 text-slate-400 shrink-0 transition-transform duration-300 group-open:rotate-180"
                    aria-hidden="true"
                  />
                </summary>
                <dd className="px-5 sm:px-6 pb-5 sm:pb-6 text-slate-600 leading-relaxed text-sm border-t border-slate-100 pt-4">
                  {faq.answer}
                </dd>
              </details>
            ))}

            {/* Generic FAQs from master list */}
            {GENERIC_FAQS.map((faq, index) => (
              <details
                key={`gen-${index}`}
                className="group border border-slate-200 rounded-2xl overflow-hidden"
              >
                <summary className="flex items-center justify-between gap-4 cursor-pointer p-5 sm:p-6 font-semibold text-slate-900 hover:bg-slate-50 transition-colors list-none [&::-webkit-details-marker]:hidden">
                  <dt className="text-left text-base">{faq.question}</dt>
                  <ChevronDown
                    className="h-5 w-5 text-slate-400 shrink-0 transition-transform duration-300 group-open:rotate-180"
                    aria-hidden="true"
                  />
                </summary>
                <dd className="px-5 sm:px-6 pb-5 sm:pb-6 text-slate-600 leading-relaxed text-sm border-t border-slate-100 pt-4">
                  {faq.answer}
                </dd>
              </details>
            ))}
          </dl>

          <div className="mt-8 text-center">
            <p className="text-slate-600 text-sm mb-4">
              Have more questions about car lift from {location.name}?
            </p>
            <Button asChild variant="outline" size="default">
              <a
                href={formatWhatsAppHref(
                  BUSINESS.whatsapp,
                  `Hi! I have a question about car lift from ${location.name}.`
                )}
                target="_blank"
                rel="noopener noreferrer"
              >
                <MessageCircle className="h-4 w-4" aria-hidden="true" />
                Ask on WhatsApp
              </a>
            </Button>
          </div>
        </div>
      </section>

      {/* ═══════════════════════════════════════════════════════════════════
          7. REVIEWS / TESTIMONIALS
      ════════════════════════════════════════════════════════════════════ */}
      <section
        aria-labelledby="reviews-heading"
        className="py-16 sm:py-20 bg-slate-50"
      >
        <div className="max-w-5xl mx-auto px-4 sm:px-6 lg:px-8">
          <div className="text-center mb-10">
            <p className="text-blue-600 font-semibold text-sm uppercase tracking-widest mb-3">
              What Riders Say
            </p>
            <h2
              id="reviews-heading"
              className="text-2xl sm:text-3xl font-extrabold text-slate-900 tracking-tight mb-4"
            >
              Real Reviews from Car Lift UAE Riders
            </h2>
          </div>

          <ul
            className="grid grid-cols-1 sm:grid-cols-3 gap-6 list-none"
            role="list"
          >
            {testimonials.map((t) => (
              <li key={t.id}>
                <Card className="h-full border-slate-200 hover:shadow-md transition-shadow">
                  <CardContent className="p-6 pt-6 flex flex-col h-full">
                    {/* Stars */}
                    <div
                      className="flex items-center gap-0.5 mb-3"
                      role="img"
                      aria-label={`${t.rating} out of 5 stars`}
                    >
                      {Array.from({ length: 5 }).map((_, i) => (
                        <Star
                          key={i}
                          className={`h-4 w-4 ${
                            i < t.rating
                              ? "fill-amber-400 text-amber-400"
                              : "fill-slate-200 text-slate-200"
                          }`}
                          aria-hidden="true"
                        />
                      ))}
                    </div>

                    {/* Review text */}
                    <blockquote className="text-slate-700 text-sm leading-relaxed flex-1 mb-4">
                      &ldquo;{t.review}&rdquo;
                    </blockquote>

                    {/* Author */}
                    <footer className="flex items-center gap-3 pt-4 border-t border-slate-100">
                      <div className="w-9 h-9 rounded-full bg-blue-100 flex items-center justify-center text-blue-700 font-bold text-sm shrink-0">
                        {t.name.charAt(0)}
                      </div>
                      <div>
                        <p className="font-bold text-slate-900 text-sm leading-none mb-0.5">
                          {t.name}
                        </p>
                        <p className="text-slate-500 text-xs">{t.role}</p>
                        <p className="text-slate-400 text-xs flex items-center gap-1 mt-0.5">
                          <MapPin className="h-3 w-3" aria-hidden="true" />
                          {t.location}
                        </p>
                      </div>
                      {t.verified && (
                        <BadgeCheck
                          className="h-5 w-5 text-blue-500 ml-auto shrink-0"
                          aria-label="Verified rider"
                        />
                      )}
                    </footer>
                  </CardContent>
                </Card>
              </li>
            ))}
          </ul>

          {/* Overall rating */}
          <div className="mt-8 text-center">
            <p className="text-slate-500 text-sm">
              Overall rating:{" "}
              <strong className="text-slate-900">{BUSINESS.rating}★</strong>{" "}
              from{" "}
              <strong className="text-slate-900">
                {BUSINESS.reviewCount}+
              </strong>{" "}
              verified riders
            </p>
          </div>
        </div>
      </section>

      {/* ═══════════════════════════════════════════════════════════════════
          8. RELATED LOCATIONS
      ════════════════════════════════════════════════════════════════════ */}
      {relatedLocations.length > 0 && (
        <section
          aria-labelledby="related-heading"
          className="py-16 sm:py-20 bg-white"
        >
          <div className="max-w-5xl mx-auto px-4 sm:px-6 lg:px-8">
            <div className="text-center mb-10">
              <p className="text-blue-600 font-semibold text-sm uppercase tracking-widest mb-3">
                Explore More
              </p>
              <h2
                id="related-heading"
                className="text-2xl sm:text-3xl font-extrabold text-slate-900 tracking-tight mb-4"
              >
                Other Car Lift Routes Near {location.name}
              </h2>
            </div>

            <ul
              className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-4 gap-4 list-none"
              role="list"
            >
              {relatedLocations.map((related) => {
                const relatedEmirate = related.emirate as Emirate;
                return (
                  <li key={related.slug}>
                    <Link
                      href={`/locations/${related.slug}`}
                      className="group flex flex-col gap-3 bg-white border border-slate-200 hover:border-blue-300 hover:shadow-md rounded-2xl p-5 transition-all duration-200 h-full"
                      aria-label={`Car lift from ${related.name}`}
                    >
                      <div className="flex items-start justify-between gap-2">
                        <h3 className="font-bold text-slate-900 text-sm leading-snug group-hover:text-blue-600 transition-colors">
                          {related.name}
                        </h3>
                        <span
                          className={`shrink-0 text-[10px] font-semibold px-2 py-0.5 rounded-full ${emirateBadgeClass[relatedEmirate]}`}
                        >
                          {emirateLabel[relatedEmirate]}
                        </span>
                      </div>

                      <div className="flex items-center justify-between text-xs text-slate-500">
                        <span className="flex items-center gap-1">
                          <Clock className="h-3 w-3" aria-hidden="true" />
                          {related.drivingTime}
                        </span>
                        <span className="font-bold text-emerald-600">
                          {emirateNormalPriceDisplay[relatedEmirate]}/trip
                        </span>
                      </div>

                      <div className="flex items-center gap-1 text-xs text-blue-500 font-medium mt-auto">
                        <span>View details</span>
                        <ArrowRight
                          className="h-3 w-3 group-hover:translate-x-0.5 transition-transform"
                          aria-hidden="true"
                        />
                      </div>
                    </Link>
                  </li>
                );
              })}
            </ul>

            <div className="text-center mt-8">
              <Button asChild variant="outline" size="default">
                <Link href="/locations">
                  View All Locations
                  <ArrowRight className="h-4 w-4" aria-hidden="true" />
                </Link>
              </Button>
            </div>
          </div>
        </section>
      )}

      {/* ═══════════════════════════════════════════════════════════════════
          9. FINAL CTA
      ════════════════════════════════════════════════════════════════════ */}
      <section
        aria-labelledby="location-cta-heading"
        className="relative overflow-hidden py-16 sm:py-20"
        style={{
          background:
            "linear-gradient(135deg, #0f172a 0%, #1e3a5f 50%, #0c2340 100%)",
        }}
      >
        <div
          className="absolute inset-0 opacity-[0.04] pointer-events-none"
          style={{
            backgroundImage:
              "radial-gradient(circle, rgba(255,255,255,0.8) 1px, transparent 1px)",
            backgroundSize: "28px 28px",
          }}
          aria-hidden="true"
        />

        <div className="relative z-10 max-w-2xl mx-auto px-4 sm:px-6 lg:px-8 text-center">
          {/* Pulsing live dot */}
          <div className="flex justify-center mb-5">
            <span className="inline-flex items-center gap-2 rounded-full bg-white/10 border border-white/15 px-4 py-1.5 text-sm font-semibold text-white/80">
              <span className="relative flex h-2 w-2" aria-hidden="true">
                <span className="animate-ping absolute inline-flex h-full w-full rounded-full bg-emerald-400 opacity-75" />
                <span className="relative inline-flex h-2 w-2 rounded-full bg-emerald-500" />
              </span>
              Seats Available Now
            </span>
          </div>

          <h2
            id="location-cta-heading"
            className="text-3xl sm:text-4xl font-extrabold text-white tracking-tight mb-4"
          >
            Book Your Car Lift from {location.name}
          </h2>
          <p className="text-slate-300 text-base sm:text-lg leading-relaxed mb-8">
            Join riders saving time and money on the{" "}
            {routeLabel} route. WhatsApp us to secure your seat — {priceDisplay}/trip.
          </p>

          <div className="flex flex-col sm:flex-row gap-4 justify-center mb-8">
            <Button asChild variant="whatsapp" size="xl">
              <a
                href={whatsappHref}
                target="_blank"
                rel="noopener noreferrer"
                aria-label={`Book car lift from ${location.name} via WhatsApp`}
              >
                <MessageCircle className="h-5 w-5" aria-hidden="true" />
                WhatsApp – Book Now
              </a>
            </Button>
            <Button
              asChild
              size="xl"
              className="border-2 border-white/40 bg-white/10 text-white hover:bg-white/20"
            >
              <a href={phoneHref} aria-label={`Call ${BUSINESS.name}`}>
                <Phone className="h-5 w-5" aria-hidden="true" />
                Call Us
              </a>
            </Button>
          </div>

          {/* Rating strip */}
          <div className="flex items-center justify-center gap-2">
            <div
              className="flex items-center gap-0.5"
              role="img"
              aria-label={`${BUSINESS.rating} out of 5 stars`}
            >
              {Array.from({ length: 5 }).map((_, i) => (
                <Star
                  key={i}
                  className="h-4 w-4 fill-amber-400 text-amber-400"
                  aria-hidden="true"
                />
              ))}
            </div>
            <p className="text-sm font-semibold text-white/80">
              {BUSINESS.rating}★ rated by{" "}
              <span className="text-white">{BUSINESS.reviewCount}+</span>{" "}
              satisfied riders
            </p>
          </div>
        </div>
      </section>
    </>
  );
}
