import type { Metadata } from "next";
import Link from "next/link";
import {
  Car,
  Clock,
  DollarSign,
  MapPin,
  CheckCircle,
  MessageCircle,
  Phone,
  ArrowRight,
  ChevronDown,
  Users,
  Star,
  Shield,
} from "lucide-react";
import { Card, CardContent } from "@/components/ui/card";
import { Button } from "@/components/ui/button";
import Breadcrumb from "@/components/sections/breadcrumb";
import SchemaScript from "@/components/sections/schema-script";
import {
  localBusinessSchema,
  faqSchema,
  breadcrumbSchema,
  serviceSchema,
  primaryImageOfPageSchema,
} from "@/lib/schema";
import { BUSINESS, formatWhatsAppHref, formatPhoneHref } from "@/lib/utils";

export const revalidate = 86400;

export const metadata: Metadata = {
  title: "Car Lift Ajman to Dubai Business Bay – AED 420/Month | +971 54 330 8261",
  description:
    "Daily car lift from Ajman to Dubai Business Bay, DIFC & JLT from AED 420/month. Salik included, GPS-tracked, 4.9★ rated. Ladies option. WhatsApp +971 54 330 8261.",
  keywords:
    "ajman to dubai car lift, car lift from ajman to dubai, ajman car lift, carlift from ajman to dubai, car lift ajman to dubai monthly, ajman dubai shared ride",
  alternates: {
    canonical: "https://www.carliftuae.com/car-lift-ajman-to-dubai",
  },
  openGraph: {
    title: "Car Lift Ajman to Dubai Business Bay – AED 420/Month | +971 54 330 8261",
    description:
      "Daily car lift from Ajman to Business Bay, DIFC & JLT from AED 420/month. Salik included, GPS-tracked. Ladies option. WhatsApp +971 54 330 8261.",
    // OG image generated by src/app/car-lift-ajman-to-dubai/opengraph-image.tsx
  },
};

const PAGE_FAQS = [
  {
    question: "How much does a car lift from Ajman to Dubai cost per month?",
    answer:
      "Monthly car lift from Ajman to Dubai Business Bay starts at AED 420/month from central Ajman areas like Al Nuaimiya and Al Rashidiya. Ajman Corniche and farther areas are AED 450–480/month. All prices include Salik toll on E311 (Emirates Road) — no hidden charges.",
  },
  {
    question: "How long is the journey from Ajman to Dubai?",
    answer:
      "The journey from central Ajman to Business Bay takes approximately 65–80 minutes via E311 (Emirates Road) passing through Sharjah. The 6:30 AM departure is fastest at 65 minutes. The 7:30–8:00 AM slot takes 75–90 minutes during peak traffic. Evening returns are typically 70–90 minutes.",
  },
  {
    question: "Which areas in Ajman does the car lift pick up from?",
    answer:
      "We pick up from Al Nuaimiya, Al Rashidiya, Al Jurf, Al Hamidiya, Ajman Corniche, Ajman City Centre area, Al Rumailah, Al Tallah, and other Ajman areas. WhatsApp your building name for a quick confirmation.",
  },
  {
    question: "What route does the car lift take from Ajman to Dubai?",
    answer:
      "Our Ajman to Dubai car lift travels via E311 (Emirates Road) passing through Sharjah, then onto Sheikh Zayed Road (E11) to reach Business Bay, DIFC, and other Dubai destinations. This is the fastest route avoiding most inland traffic bottlenecks.",
  },
  {
    question: "Which Dubai destinations does the Ajman car lift serve?",
    answer:
      "We serve Business Bay, DIFC, JLT (Jumeirah Lakes Towers), Dubai Marina, Al Barsha, JVC, Deira, and more. The destination affects the final monthly price — Business Bay (AED 420/mo) is closer than JLT and Dubai Marina (AED 450–480/mo from Ajman).",
  },
  {
    question: "Is there a ladies-only car lift from Ajman to Dubai?",
    answer:
      "Yes. A ladies-only car lift from Ajman to Dubai is available on request, with either a verified female driver or a ladies-only vehicle. The same price applies as the standard service — WhatsApp us to arrange.",
  },
];

const TIMINGS = [
  { label: "Ajman → Dubai (Morning)", times: ["6:30 AM", "7:00 AM", "7:30 AM", "8:00 AM"], color: "bg-sky-700" },
  { label: "Dubai → Ajman (Evening)", times: ["5:00 PM", "5:30 PM", "6:00 PM", "6:30 PM"], color: "bg-slate-800" },
];

const PICKUP_AREAS = [
  "Al Nuaimiya", "Al Rashidiya", "Al Jurf",
  "Al Hamidiya", "Ajman Corniche", "Ajman City Centre",
  "Al Rumailah", "Al Tallah", "Al Mowaihat", "Al Zahra",
];

const PRICING_AREAS = [
  { area: "Al Nuaimiya / Al Rashidiya", price: "AED 420", note: "Central Ajman" },
  { area: "Al Jurf / Al Hamidiya", price: "AED 430", note: "" },
  { area: "Ajman City Centre area", price: "AED 440", note: "" },
  { area: "Ajman Corniche", price: "AED 450", note: "Farther zone" },
  { area: "Al Mowaihat / Al Tallah", price: "AED 460+", note: "Farther zone" },
];

const COST_COMPARISON = [
  { item: "Fuel (Ajman → Dubai daily, 26 days)", driving: "AED 720", carlift: "—" },
  { item: "Salik tolls (E311 + E11)", driving: "AED 390", carlift: "Included" },
  { item: "Parking in Business Bay", driving: "AED 520", carlift: "—" },
  { item: "Total monthly cost", driving: "AED 1,630+", carlift: "AED 420", highlight: true },
];

export default function CarLiftAjmanToDubaiPage() {
  const whatsappHref = formatWhatsAppHref(
    BUSINESS.whatsapp,
    "Hi! I want to book car lift from Ajman to Dubai."
  );
  const phoneHref = formatPhoneHref(BUSINESS.phone);

  const schemas = [
    localBusinessSchema(),
    serviceSchema({
      name: "Car Lift Ajman to Dubai",
      description:
        "Daily car lift from Ajman to Dubai Business Bay, DIFC, and JLT. Monthly packages from AED 420/month via E311. Salik included, GPS-tracked.",
      url: "/car-lift-ajman-to-dubai",
      price: "420",
    }),
    faqSchema(PAGE_FAQS),
    breadcrumbSchema([
      { name: "Home", url: "/" },
      { name: "Car Lift Ajman to Dubai", url: "/car-lift-ajman-to-dubai" },
    ]),
    primaryImageOfPageSchema({
      imageUrl: "/images/locations/sharjah/sharjah-car-lift-morning-pickup.webp",
      pageUrl: "/car-lift-ajman-to-dubai",
      caption: "Car lift pickup from Ajman – daily morning departure to Dubai Business Bay",
    }),
  ];

  return (
    <>
      <SchemaScript schema={schemas} />

      {/* ── Hero ─────────────────────────────────────────────────────────── */}
      <section
        aria-labelledby="hero-heading"
        className="relative overflow-hidden py-16 sm:py-20"
        style={{ background: "linear-gradient(135deg, #0c4a6e 0%, #075985 50%, #082f49 100%)" }}
      >
        <div
          className="absolute inset-0 opacity-[0.04] pointer-events-none"
          style={{ backgroundImage: "radial-gradient(circle, rgba(255,255,255,0.8) 1px, transparent 1px)", backgroundSize: "28px 28px" }}
          aria-hidden="true"
        />
        <div className="relative z-10 max-w-5xl mx-auto px-4 sm:px-6 lg:px-8">
          <Breadcrumb
            items={[{ label: "Home", href: "/" }, { label: "Car Lift Ajman to Dubai" }]}
            className="mb-6 [&_*]:text-sky-400 [&_a]:text-sky-300 [&_a:hover]:text-white"
          />
          <div className="flex flex-col lg:flex-row lg:items-start lg:justify-between gap-10">
            <div className="flex-1">
              <div className="inline-flex items-center gap-2 bg-sky-500/20 border border-sky-400/30 rounded-full px-4 py-1.5 text-sm text-sky-300 font-semibold mb-5">
                <Car className="h-4 w-4" aria-hidden="true" />
                From AED 420/month · E311 Route · Salik Included
              </div>
              <h1 id="hero-heading" className="text-3xl sm:text-4xl lg:text-5xl font-extrabold text-white tracking-tight leading-tight mb-4">
                Car Lift Ajman to Dubai<br className="hidden sm:block" /> Business Bay
              </h1>
              <p className="text-sky-100 text-base sm:text-lg leading-relaxed mb-3 max-w-xl">
                Daily shared car lift from all major Ajman areas to Dubai Business Bay, DIFC, and JLT.
                Via E311 Emirates Road — the fastest Ajman to Dubai route, Salik included.
              </p>
              <p className="text-sky-200/80 text-sm leading-relaxed mb-6 max-w-xl">
                Driving yourself from Ajman to Dubai costs AED 1,630+/month in fuel, Salik, and parking.
                Our monthly car lift starts at AED 420 — everything included.
              </p>
              <ul className="grid grid-cols-2 sm:grid-cols-4 gap-3 mb-8" role="list" aria-label="Key route stats">
                {[
                  { icon: DollarSign, label: "From AED 420", sub: "/month" },
                  { icon: Clock, label: "65–80 min", sub: "Journey Time" },
                  { icon: Car, label: "E311 Route", sub: "Emirates Rd" },
                  { icon: Users, label: "Ladies Option", sub: "Available" },
                ].map(({ icon: Icon, label, sub }) => (
                  <li key={sub} className="bg-white/10 border border-white/15 rounded-xl p-4 text-center">
                    <Icon className="h-5 w-5 text-sky-400 mx-auto mb-1.5" aria-hidden="true" />
                    <p className="text-white font-extrabold text-base leading-none">{label}</p>
                    <p className="text-sky-200/70 text-xs mt-1">{sub}</p>
                  </li>
                ))}
              </ul>
              <div className="flex flex-col sm:flex-row gap-3">
                <Button asChild variant="whatsapp" size="lg">
                  <a href={whatsappHref} target="_blank" rel="noopener noreferrer" aria-label="Book car lift from Ajman to Dubai via WhatsApp">
                    <MessageCircle className="h-5 w-5" aria-hidden="true" />
                    Book via WhatsApp
                  </a>
                </Button>
                <Button asChild size="lg" className="border-2 border-white/30 bg-white/10 text-white hover:bg-white/20">
                  <a href={phoneHref} aria-label="Call Car Lift UAE">
                    <Phone className="h-5 w-5" aria-hidden="true" />
                    Call {BUSINESS.phone}
                  </a>
                </Button>
              </div>
            </div>
            <aside className="lg:w-72 bg-white/10 border border-white/15 backdrop-blur-sm rounded-2xl p-6 shrink-0" aria-label="What is included">
              <p className="text-white font-bold text-base mb-4 flex items-center gap-2">
                <CheckCircle className="h-5 w-5 text-sky-400" aria-hidden="true" />
                What&apos;s Included
              </p>
              <ul className="space-y-3" role="list">
                {[
                  "Morning & evening rides",
                  "Salik E311 & E11 tolls included",
                  "GPS-tracked vehicle",
                  "Verified UAE driver",
                  "Air-conditioned vehicle",
                  "WhatsApp support 24/7",
                  "Ladies-only option",
                  "Reserved monthly seat",
                ].map((item) => (
                  <li key={item} className="flex items-center gap-2.5">
                    <CheckCircle className="h-4 w-4 text-sky-400 shrink-0" aria-hidden="true" />
                    <span className="text-sky-100 text-sm">{item}</span>
                  </li>
                ))}
              </ul>
            </aside>
          </div>
        </div>
      </section>

      {/* ── Cost Comparison ──────────────────────────────────────────────── */}
      <section aria-labelledby="cost-heading" className="py-14 sm:py-16 bg-white">
        <div className="max-w-5xl mx-auto px-4 sm:px-6 lg:px-8">
          <div className="text-center mb-10">
            <p className="text-sky-600 font-semibold text-sm uppercase tracking-widest mb-3">Real Savings</p>
            <h2 id="cost-heading" className="text-2xl sm:text-3xl font-extrabold text-slate-900 tracking-tight mb-3">
              Driving from Ajman to Dubai Costs AED 1,600+/Month
            </h2>
            <p className="text-slate-600 max-w-xl mx-auto text-sm">
              The distance is longer than Sharjah, which means even higher fuel and Salik bills. Here is the real monthly cost comparison:
            </p>
          </div>
          <div className="border border-slate-200 rounded-2xl overflow-hidden max-w-2xl mx-auto mb-8">
            <table className="w-full text-sm" aria-label="Cost comparison Ajman driving vs car lift">
              <thead className="bg-slate-50 border-b border-slate-200">
                <tr>
                  <th className="text-left px-4 py-3 font-semibold text-slate-700">Monthly Cost Item</th>
                  <th className="text-right px-4 py-3 font-semibold text-red-600">Driving Yourself</th>
                  <th className="text-right px-4 py-3 font-semibold text-emerald-600">Car Lift UAE</th>
                </tr>
              </thead>
              <tbody>
                {COST_COMPARISON.map((row, i) => (
                  <tr key={row.item} className={row.highlight ? "bg-emerald-50 font-bold border-t-2 border-emerald-200" : i % 2 === 0 ? "bg-white" : "bg-slate-50/50"}>
                    <td className="px-4 py-3 text-slate-800">{row.item}</td>
                    <td className="px-4 py-3 text-right text-red-600">{row.driving}</td>
                    <td className="px-4 py-3 text-right text-emerald-600">{row.carlift}</td>
                  </tr>
                ))}
              </tbody>
            </table>
          </div>
          <div className="text-center">
            <Button asChild variant="whatsapp" size="default">
              <a href={whatsappHref} target="_blank" rel="noopener noreferrer">
                <MessageCircle className="h-4 w-4" aria-hidden="true" />
                Save AED 1,200/Month – WhatsApp Now
              </a>
            </Button>
          </div>
        </div>
      </section>

      {/* ── Timings ─────────────────────────────────────────────────────── */}
      <section aria-labelledby="timings-heading" className="py-14 sm:py-16 bg-slate-50">
        <div className="max-w-5xl mx-auto px-4 sm:px-6 lg:px-8">
          <div className="text-center mb-10">
            <p className="text-sky-600 font-semibold text-sm uppercase tracking-widest mb-3">Daily Schedule</p>
            <h2 id="timings-heading" className="text-2xl sm:text-3xl font-extrabold text-slate-900 tracking-tight mb-3">
              Ajman to Dubai Car Lift Timings
            </h2>
            <p className="text-slate-600 max-w-xl mx-auto text-sm">
              Fixed departures Monday to Saturday. Your seat is reserved for the same slot every day.
            </p>
          </div>
          <div className="grid grid-cols-1 sm:grid-cols-2 gap-6">
            {TIMINGS.map((t) => (
              <Card key={t.label} className="border-slate-200">
                <CardContent className="p-6 pt-6">
                  <div className="flex items-center gap-3 mb-5">
                    <div className={`w-9 h-9 rounded-xl ${t.color} flex items-center justify-center shrink-0`}>
                      <Clock className="h-5 w-5 text-white" aria-hidden="true" />
                    </div>
                    <h3 className="font-bold text-slate-900 text-sm">{t.label}</h3>
                  </div>
                  <div className="grid grid-cols-2 gap-3">
                    {t.times.map((time) => (
                      <div key={time} className="bg-slate-50 border border-slate-200 rounded-xl p-3 text-center">
                        <p className="font-extrabold text-slate-900 text-xl">{time}</p>
                      </div>
                    ))}
                  </div>
                </CardContent>
              </Card>
            ))}
          </div>
        </div>
      </section>

      {/* ── Pickup Areas & Pricing ───────────────────────────────────────── */}
      <section aria-labelledby="pricing-heading" className="py-14 sm:py-16 bg-white">
        <div className="max-w-5xl mx-auto px-4 sm:px-6 lg:px-8">
          <div className="text-center mb-10">
            <p className="text-sky-600 font-semibold text-sm uppercase tracking-widest mb-3">Transparent Pricing</p>
            <h2 id="pricing-heading" className="text-2xl sm:text-3xl font-extrabold text-slate-900 tracking-tight mb-3">
              Monthly Car Lift Pricing by Ajman Area
            </h2>
          </div>
          <div className="grid grid-cols-1 lg:grid-cols-2 gap-8 items-start">
            <div>
              <h3 className="text-base font-bold text-slate-900 mb-4 flex items-center gap-2">
                <MapPin className="h-5 w-5 text-sky-500" aria-hidden="true" />
                Ajman Pickup Areas
              </h3>
              <ul className="grid grid-cols-1 sm:grid-cols-2 gap-2 mb-4 list-none" role="list">
                {PICKUP_AREAS.map((area) => (
                  <li key={area} className="flex items-center gap-2.5 bg-slate-50 border border-slate-200 rounded-xl px-3 py-2.5">
                    <CheckCircle className="h-4 w-4 text-sky-500 shrink-0" aria-hidden="true" />
                    <span className="text-slate-800 font-medium text-sm">{area}</span>
                  </li>
                ))}
              </ul>
              <p className="text-slate-500 text-xs italic">Not listed? WhatsApp us — we cover all of Ajman.</p>
            </div>
            <div>
              <h3 className="text-base font-bold text-slate-900 mb-4 flex items-center gap-2">
                <DollarSign className="h-5 w-5 text-emerald-500" aria-hidden="true" />
                Monthly Pricing by Area
              </h3>
              <div className="border border-slate-200 rounded-2xl overflow-hidden mb-4">
                <table className="w-full text-sm" aria-label="Car lift Ajman to Dubai pricing by area">
                  <thead className="bg-slate-50 border-b border-slate-200">
                    <tr>
                      <th className="text-left px-4 py-3 font-semibold text-slate-700">Pickup Area (Ajman)</th>
                      <th className="text-right px-4 py-3 font-semibold text-slate-700">Monthly Price</th>
                    </tr>
                  </thead>
                  <tbody>
                    {PRICING_AREAS.map((row, i) => (
                      <tr key={row.area} className={i % 2 === 0 ? "bg-white" : "bg-slate-50/50"}>
                        <td className="px-4 py-3 text-slate-800 font-medium">
                          {row.area}
                          {row.note && <span className="ml-2 text-xs text-slate-400">({row.note})</span>}
                        </td>
                        <td className="px-4 py-3 text-right font-extrabold text-emerald-600">{row.price}</td>
                      </tr>
                    ))}
                  </tbody>
                </table>
              </div>
              <Card className="border-sky-200 bg-sky-50">
                <CardContent className="p-4 pt-4">
                  <div className="flex items-start gap-3">
                    <div className="w-9 h-9 rounded-full bg-sky-600 flex items-center justify-center shrink-0">
                      <Shield className="h-4 w-4 text-white" aria-hidden="true" />
                    </div>
                    <div>
                      <p className="font-bold text-sky-900 text-sm mb-1">All Salik Tolls Included</p>
                      <p className="text-sky-700 text-xs leading-relaxed">
                        E311 (Emirates Road) and E11 (Sheikh Zayed Road) Salik gates are included in every monthly package. No surprise charges.
                      </p>
                    </div>
                  </div>
                </CardContent>
              </Card>
              <Button asChild variant="whatsapp" size="default" className="w-full mt-4">
                <a href={whatsappHref} target="_blank" rel="noopener noreferrer">
                  <MessageCircle className="h-4 w-4" aria-hidden="true" />
                  Get Your Exact Price – WhatsApp
                </a>
              </Button>
            </div>
          </div>
        </div>
      </section>

      {/* ── FAQ ─────────────────────────────────────────────────────────── */}
      <section aria-labelledby="faq-heading" className="py-14 sm:py-16 bg-slate-50">
        <div className="max-w-3xl mx-auto px-4 sm:px-6 lg:px-8">
          <div className="text-center mb-10">
            <p className="text-sky-600 font-semibold text-sm uppercase tracking-widest mb-3">FAQs</p>
            <h2 id="faq-heading" className="text-2xl sm:text-3xl font-extrabold text-slate-900 tracking-tight mb-3">
              Ajman to Dubai Car Lift – Common Questions
            </h2>
          </div>
          <dl className="space-y-4">
            {PAGE_FAQS.map((faq, i) => (
              <details key={i} className="group border border-slate-200 rounded-2xl overflow-hidden bg-white">
                <summary className="flex items-center justify-between gap-4 cursor-pointer p-5 font-semibold text-slate-900 hover:bg-slate-50 transition-colors list-none [&::-webkit-details-marker]:hidden">
                  <dt className="text-left text-base">{faq.question}</dt>
                  <ChevronDown className="h-5 w-5 text-slate-400 shrink-0 transition-transform duration-300 group-open:rotate-180" aria-hidden="true" />
                </summary>
                <dd className="px-5 pb-5 text-slate-600 leading-relaxed text-sm border-t border-slate-100 pt-4">
                  {faq.answer}
                </dd>
              </details>
            ))}
          </dl>
        </div>
      </section>

      {/* ── Related pages ────────────────────────────────────────────────── */}
      <section aria-label="Related car lift pages" className="py-12 bg-white">
        <div className="max-w-5xl mx-auto px-4 sm:px-6 lg:px-8">
          <h2 className="text-xl font-bold text-slate-900 mb-6 text-center">Related Car Lift Services</h2>
          <ul className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-4 gap-4 list-none" role="list">
            {[
              { href: "/car-lift-from-sharjah-to-business-bay", label: "Car Lift Sharjah to Business Bay", desc: "Full route guide & pricing" },
              { href: "/carlift-sharjah-to-dubai-business-bay", label: "Carlift Sharjah to Dubai", desc: "Dubai-wide monthly pricing" },
              { href: "/ladies-car-lift-sharjah-to-dubai", label: "Ladies Car Lift", desc: "Female driver, ladies-only option" },
              { href: "/monthly-pick-and-drop-service-sharjah", label: "Monthly Pick & Drop", desc: "26-day subscription, both ways" },
            ].map(({ href, label, desc }) => (
              <li key={href}>
                <Link href={href} className="group flex flex-col gap-2 p-5 border border-slate-200 hover:border-sky-300 rounded-2xl hover:shadow-md transition-all h-full">
                  <span className="font-bold text-slate-900 group-hover:text-sky-600 text-sm">{label}</span>
                  <span className="text-slate-500 text-xs flex-1">{desc}</span>
                  <span className="text-sky-500 text-xs font-medium flex items-center gap-1 mt-2">
                    Learn more <ArrowRight className="h-3 w-3" aria-hidden="true" />
                  </span>
                </Link>
              </li>
            ))}
          </ul>
        </div>
      </section>

      {/* ── Final CTA ────────────────────────────────────────────────────── */}
      <section aria-label="Book Ajman to Dubai car lift" className="py-14 bg-sky-700">
        <div className="max-w-xl mx-auto px-4 text-center">
          <div className="flex items-center justify-center gap-0.5 mb-3" role="img" aria-label="4.9 out of 5 stars">
            {Array.from({ length: 5 }).map((_, i) => (
              <Star key={i} className="h-5 w-5 fill-amber-400 text-amber-400" aria-hidden="true" />
            ))}
          </div>
          <h2 className="text-white font-extrabold text-2xl sm:text-3xl mb-3">
            Book Your Ajman to Dubai Car Lift Today
          </h2>
          <p className="text-sky-100 text-sm mb-6">
            {BUSINESS.reviewCount}+ daily riders trust Car Lift UAE. Ajman seats fill fast — WhatsApp now to secure yours.
          </p>
          <div className="flex flex-col sm:flex-row gap-3 justify-center">
            <Button asChild size="xl" className="bg-white text-sky-700 hover:bg-sky-50 font-bold">
              <a href={whatsappHref} target="_blank" rel="noopener noreferrer" aria-label="Book car lift Ajman to Dubai">
                <MessageCircle className="h-5 w-5" aria-hidden="true" />
                WhatsApp – Book Now
              </a>
            </Button>
            <Button asChild size="xl" className="border-2 border-white/40 bg-white/10 text-white hover:bg-white/20">
              <a href={phoneHref}>
                <Phone className="h-5 w-5" aria-hidden="true" />
                Call {BUSINESS.phone}
              </a>
            </Button>
          </div>
        </div>
      </section>
    </>
  );
}
