import type { Metadata } from "next";
import Link from "next/link";
import {
  Car,
  Clock,
  DollarSign,
  MapPin,
  CheckCircle,
  MessageCircle,
  Phone,
  ArrowRight,
  ChevronDown,
  Users,
  Star,
  Shield,
} from "lucide-react";
import { Card, CardContent } from "@/components/ui/card";
import { Button } from "@/components/ui/button";
import Breadcrumb from "@/components/sections/breadcrumb";
import SchemaScript from "@/components/sections/schema-script";
import {
  localBusinessSchema,
  faqSchema,
  breadcrumbSchema,
  serviceSchema,
  primaryImageOfPageSchema,
} from "@/lib/schema";
import { BUSINESS, formatWhatsAppHref, formatPhoneHref } from "@/lib/utils";

export const revalidate = 86400;

export const metadata: Metadata = {
  title: "Carlift Sharjah to JLT – Jumeirah Lakes Towers | AED 130 Sharing / AED 200 Private | +971 54 330 8261",
  description:
    "Daily carlift from Sharjah to JLT (Jumeirah Lakes Towers) from AED 130 sharing / AED 200 private. Salik included, GPS-tracked, 4.9★ rated. Also covers Dubai Marina & JVC. WhatsApp +971 54 330 8261.",
  keywords:
    "sharjah to jlt car lift, car lift sharjah to jlt, carlift sharjah to jlt, carlift to jlt, jlt car lift from sharjah, sharjah jlt monthly car lift",
  alternates: {
    canonical: "https://www.carliftuae.com/carlift-sharjah-to-jlt",
  },
  openGraph: {
    title: "Carlift Sharjah to JLT – Jumeirah Lakes Towers | AED 130 Sharing / AED 200 Private | +971 54 330 8261",
    description:
      "Daily carlift Sharjah to JLT from AED 130 sharing / AED 200 private. Cluster A–D drop-off. Also Dubai Marina & JVC. Salik included. WhatsApp +971 54 330 8261.",
    // OG image generated by src/app/carlift-sharjah-to-jlt/opengraph-image.tsx
  },
};

const PAGE_FAQS = [
  {
    question: "How much does a carlift from Sharjah to JLT cost per month?",
    answer:
      "Monthly carlift from Sharjah to JLT (Jumeirah Lakes Towers) starts at AED 130 sharing / AED 200 private from Al Nahda, Sharjah. Muweilah and areas farther from Dubai are AED 130 sharing–450/month. All prices include Salik toll on Sheikh Zayed Road — no hidden charges.",
  },
  {
    question: "Where exactly does the carlift drop off in JLT?",
    answer:
      "We drop off at any JLT Cluster — Cluster A, B, C, D, E, F, G, and beyond — as well as DMCC Metro Station if you prefer to walk to your tower. Just share your tower name when you book and we will confirm the exact drop-off point.",
  },
  {
    question: "How long does the journey from Sharjah to JLT take?",
    answer:
      "The journey from Al Nahda, Sharjah to JLT takes 55–75 minutes via Sheikh Zayed Road (E11). The 6:30 AM departure is fastest at 55–60 minutes. The 7:30–8:00 AM slot takes 70–80 minutes due to peak traffic on SZR.",
  },
  {
    question: "Does the JLT carlift also cover Dubai Marina and JVC?",
    answer:
      "Yes. Because JLT, Dubai Marina, and JVC are in the same cluster along Sheikh Zayed Road, we can cover all three. Dubai Marina is AED 400/month from Al Nahda; JVC is AED 390/month. WhatsApp to confirm your specific building.",
  },
  {
    question: "What time does the carlift from Sharjah to JLT depart?",
    answer:
      "Morning departures from Sharjah: 6:30 AM, 7:00 AM, 7:30 AM, and 8:00 AM. Evening return from JLT/Marina to Sharjah: 5:00 PM, 5:30 PM, 6:00 PM, and 6:30 PM. Choose your slot at booking — it is reserved for your seat every day.",
  },
  {
    question: "Is there a ladies-only carlift from Sharjah to JLT?",
    answer:
      "Yes. A ladies-only carlift from Sharjah to JLT is available on request with a verified female driver or a ladies-only vehicle. The monthly price is the same as the standard service — WhatsApp us to arrange it.",
  },
];

const TIMINGS = [
  { label: "Sharjah → JLT / Marina (Morning)", times: ["6:30 AM", "7:00 AM", "7:30 AM", "8:00 AM"], color: "bg-cyan-700" },
  { label: "JLT / Marina → Sharjah (Evening)", times: ["5:00 PM", "5:30 PM", "6:00 PM", "6:30 PM"], color: "bg-slate-800" },
];

const PICKUP_AREAS = [
  "Al Nahda (Sharjah)", "Al Taawun", "Al Khan", "Al Majaz",
  "Muweilah", "University City", "Al Zahia", "Rolla Area",
  "Al Qasimia", "Industrial Area 1–3",
];

const DROP_OFF_POINTS = [
  "JLT Cluster A", "JLT Cluster B", "JLT Cluster C", "JLT Cluster D",
  "DMCC Metro Station", "Dubai Marina Walk", "JVC Circle Mall area", "Al Barsha",
];

const PRICING_AREAS = [
  { area: "Al Nahda", price: "AED 130 sharing", note: "JLT" },
  { area: "Al Nahda", price: "AED 390", note: "JVC" },
  { area: "Al Nahda", price: "AED 400", note: "Dubai Marina" },
  { area: "Muweilah / University City", price: "AED 130 sharing", note: "JLT" },
  { area: "Muweilah / University City", price: "AED 130 sharing+", note: "Marina" },
];

const COST_COMPARISON = [
  { label: "JLT parking (AED 30–60/day × 26 days)", amount: "AED 780–1,560", highlight: false },
  { label: "Fuel Sharjah–JLT–Sharjah monthly", amount: "AED 560", highlight: false },
  { label: "Salik gates (SZR tolls)", amount: "AED 390", highlight: false },
  { label: "Total driving cost", amount: "AED 1,730–2,510", highlight: true },
  { label: "Car Lift UAE monthly (Al Nahda to JLT)", amount: "AED 130 sharing", highlight: true },
];

export default function CarliftSharjahToJltPage() {
  const whatsappHref = formatWhatsAppHref(
    BUSINESS.whatsapp,
    "Hi! I want to book carlift from Sharjah to JLT."
  );
  const phoneHref = formatPhoneHref(BUSINESS.phone);

  const schemas = [
    localBusinessSchema(),
    serviceSchema({
      name: "Carlift Sharjah to JLT",
      description:
        "Daily carlift from Sharjah to Jumeirah Lakes Towers (JLT), Dubai Marina, and JVC. Monthly packages from AED 130 sharing / AED 200 private. Salik included, GPS-tracked.",
      url: "/carlift-sharjah-to-jlt",
      price: "380",
    }),
    faqSchema(PAGE_FAQS),
    breadcrumbSchema([
      { name: "Home", url: "/" },
      { name: "Carlift Sharjah to JLT", url: "/carlift-sharjah-to-jlt" },
    ]),
    primaryImageOfPageSchema({
      imageUrl: "/images/hero/carlift-uae-route-dubai-skyline.webp",
      pageUrl: "/carlift-sharjah-to-jlt",
      caption: "Carlift from Sharjah to JLT Dubai – daily van on highway passing Dubai skyline",
    }),
  ];

  return (
    <>
      <SchemaScript schema={schemas} />

      {/* ── Hero ─────────────────────────────────────────────────────────── */}
      <section
        aria-labelledby="hero-heading"
        className="relative overflow-hidden py-16 sm:py-20"
        style={{ background: "linear-gradient(135deg, #164e63 0%, #0e7490 50%, #083344 100%)" }}
      >
        <div
          className="absolute inset-0 opacity-[0.04] pointer-events-none"
          style={{ backgroundImage: "radial-gradient(circle, rgba(255,255,255,0.8) 1px, transparent 1px)", backgroundSize: "28px 28px" }}
          aria-hidden="true"
        />
        <div className="relative z-10 max-w-5xl mx-auto px-4 sm:px-6 lg:px-8">
          <Breadcrumb
            items={[{ label: "Home", href: "/" }, { label: "Carlift Sharjah to JLT" }]}
            className="mb-6 [&_*]:text-cyan-400 [&_a]:text-cyan-300 [&_a:hover]:text-white"
          />
          <div className="flex flex-col lg:flex-row lg:items-start lg:justify-between gap-10">
            <div className="flex-1">
              <div className="inline-flex items-center gap-2 bg-cyan-500/20 border border-cyan-400/30 rounded-full px-4 py-1.5 text-sm text-cyan-300 font-semibold mb-5">
                <Car className="h-4 w-4" aria-hidden="true" />
                From AED 130 sharing / AED 200 private · Cluster A–D Drop-off · Marina &amp; JVC too
              </div>
              <h1 id="hero-heading" className="text-3xl sm:text-4xl lg:text-5xl font-extrabold text-white tracking-tight leading-tight mb-4">
                Carlift Sharjah to JLT<br className="hidden sm:block" /> Jumeirah Lakes Towers
              </h1>
              <p className="text-cyan-100 text-base sm:text-lg leading-relaxed mb-3 max-w-xl">
                Daily carlift from all major Sharjah areas to JLT, Dubai Marina, and JVC via Sheikh Zayed Road.
                Drop-off at any JLT Cluster or DMCC Metro Station. Salik included.
              </p>
              <p className="text-cyan-200/80 text-sm leading-relaxed mb-6 max-w-xl">
                JLT parking costs AED 780–1,560/month. Skip the parking stress and commute from Sharjah for just AED 130 sharing / AED 200 private — everything included.
              </p>
              <ul className="grid grid-cols-2 sm:grid-cols-4 gap-3 mb-8" role="list" aria-label="Key route stats">
                {[
                  { icon: DollarSign, label: "From AED 130 sharing", sub: "/month" },
                  { icon: Clock, label: "55–75 min", sub: "Journey Time" },
                  { icon: Car, label: "SZR Route", sub: "Sheikh Zayed Rd" },
                  { icon: Users, label: "JLT + Marina", sub: "+ JVC" },
                ].map(({ icon: Icon, label, sub }) => (
                  <li key={sub} className="bg-white/10 border border-white/15 rounded-xl p-4 text-center">
                    <Icon className="h-5 w-5 text-cyan-400 mx-auto mb-1.5" aria-hidden="true" />
                    <p className="text-white font-extrabold text-base leading-none">{label}</p>
                    <p className="text-cyan-200/70 text-xs mt-1">{sub}</p>
                  </li>
                ))}
              </ul>
              <div className="flex flex-col sm:flex-row gap-3">
                <Button asChild variant="whatsapp" size="lg">
                  <a href={whatsappHref} target="_blank" rel="noopener noreferrer" aria-label="Book carlift Sharjah to JLT via WhatsApp">
                    <MessageCircle className="h-5 w-5" aria-hidden="true" />
                    Book via WhatsApp
                  </a>
                </Button>
                <Button asChild size="lg" className="border-2 border-white/30 bg-white/10 text-white hover:bg-white/20">
                  <a href={phoneHref} aria-label="Call Car Lift UAE">
                    <Phone className="h-5 w-5" aria-hidden="true" />
                    Call {BUSINESS.phone}
                  </a>
                </Button>
              </div>
            </div>
            <aside className="lg:w-72 bg-white/10 border border-white/15 backdrop-blur-sm rounded-2xl p-6 shrink-0" aria-label="What is included">
              <p className="text-white font-bold text-base mb-4 flex items-center gap-2">
                <CheckCircle className="h-5 w-5 text-cyan-400" aria-hidden="true" />
                What&apos;s Included
              </p>
              <ul className="space-y-3" role="list">
                {[
                  "Morning & evening rides",
                  "Salik SZR tolls included",
                  "JLT Cluster drop-off",
                  "GPS-tracked vehicle",
                  "Verified UAE driver",
                  "Air-conditioned vehicle",
                  "WhatsApp support 24/7",
                  "Ladies-only option",
                ].map((item) => (
                  <li key={item} className="flex items-center gap-2.5">
                    <CheckCircle className="h-4 w-4 text-cyan-400 shrink-0" aria-hidden="true" />
                    <span className="text-cyan-100 text-sm">{item}</span>
                  </li>
                ))}
              </ul>
            </aside>
          </div>
        </div>
      </section>

      {/* ── Cost Comparison ──────────────────────────────────────────────── */}
      <section aria-labelledby="cost-heading" className="py-14 sm:py-16 bg-white">
        <div className="max-w-5xl mx-auto px-4 sm:px-6 lg:px-8">
          <div className="text-center mb-10">
            <p className="text-cyan-600 font-semibold text-sm uppercase tracking-widest mb-3">Why Car Lift Wins</p>
            <h2 id="cost-heading" className="text-2xl sm:text-3xl font-extrabold text-slate-900 tracking-tight mb-3">
              JLT Parking Costs Up to AED 1,560/Month Alone
            </h2>
            <p className="text-slate-600 max-w-xl mx-auto text-sm">
              Parking in Jumeirah Lakes Towers ranges from AED 30 to AED 60 per day. Add fuel and Salik and your monthly commute bill quickly becomes unaffordable.
            </p>
          </div>
          <div className="max-w-xl mx-auto space-y-3 mb-8">
            {COST_COMPARISON.map((row) => (
              <div key={row.label} className={`flex items-center justify-between gap-4 rounded-xl px-5 py-3.5 border ${row.highlight ? "bg-cyan-50 border-cyan-200 font-bold" : "bg-slate-50 border-slate-200"}`}>
                <span className={`text-sm ${row.highlight ? "text-cyan-900" : "text-slate-700"}`}>{row.label}</span>
                <span className={`text-sm font-bold shrink-0 ${row.highlight ? "text-cyan-600" : "text-slate-600"}`}>{row.amount}</span>
              </div>
            ))}
          </div>
          <div className="text-center">
            <Button asChild variant="whatsapp" size="default">
              <a href={whatsappHref} target="_blank" rel="noopener noreferrer">
                <MessageCircle className="h-4 w-4" aria-hidden="true" />
                Switch to AED 130 Sharing / AED 200 Private – WhatsApp Now
              </a>
            </Button>
          </div>
        </div>
      </section>

      {/* ── Timings ─────────────────────────────────────────────────────── */}
      <section aria-labelledby="timings-heading" className="py-14 sm:py-16 bg-slate-50">
        <div className="max-w-5xl mx-auto px-4 sm:px-6 lg:px-8">
          <div className="text-center mb-10">
            <p className="text-cyan-600 font-semibold text-sm uppercase tracking-widest mb-3">Daily Schedule</p>
            <h2 id="timings-heading" className="text-2xl sm:text-3xl font-extrabold text-slate-900 tracking-tight mb-3">
              Sharjah to JLT Carlift Timings
            </h2>
          </div>
          <div className="grid grid-cols-1 sm:grid-cols-2 gap-6">
            {TIMINGS.map((t) => (
              <Card key={t.label} className="border-slate-200">
                <CardContent className="p-6 pt-6">
                  <div className="flex items-center gap-3 mb-5">
                    <div className={`w-9 h-9 rounded-xl ${t.color} flex items-center justify-center shrink-0`}>
                      <Clock className="h-5 w-5 text-white" aria-hidden="true" />
                    </div>
                    <h3 className="font-bold text-slate-900 text-sm">{t.label}</h3>
                  </div>
                  <div className="grid grid-cols-2 gap-3">
                    {t.times.map((time) => (
                      <div key={time} className="bg-slate-50 border border-slate-200 rounded-xl p-3 text-center">
                        <p className="font-extrabold text-slate-900 text-xl">{time}</p>
                      </div>
                    ))}
                  </div>
                </CardContent>
              </Card>
            ))}
          </div>
        </div>
      </section>

      {/* ── Pickup & Drop-off ────────────────────────────────────────────── */}
      <section aria-labelledby="pickup-heading" className="py-14 sm:py-16 bg-white">
        <div className="max-w-5xl mx-auto px-4 sm:px-6 lg:px-8">
          <div className="text-center mb-10">
            <p className="text-cyan-600 font-semibold text-sm uppercase tracking-widest mb-3">Route Coverage</p>
            <h2 id="pickup-heading" className="text-2xl sm:text-3xl font-extrabold text-slate-900 tracking-tight mb-3">
              Pickup in Sharjah · Drop-off in JLT, Marina &amp; JVC
            </h2>
          </div>
          <div className="grid grid-cols-1 lg:grid-cols-2 gap-8">
            <div>
              <h3 className="text-lg font-bold text-slate-900 mb-4 flex items-center gap-2">
                <MapPin className="h-5 w-5 text-cyan-500" aria-hidden="true" />
                Pickup Areas (Sharjah)
              </h3>
              <ul className="grid grid-cols-1 sm:grid-cols-2 gap-3 list-none" role="list">
                {PICKUP_AREAS.map((area) => (
                  <li key={area} className="flex items-center gap-3 bg-slate-50 border border-slate-200 rounded-xl px-4 py-3">
                    <CheckCircle className="h-4 w-4 text-emerald-500 shrink-0" aria-hidden="true" />
                    <span className="text-slate-800 font-medium text-sm">{area}</span>
                  </li>
                ))}
              </ul>
              <p className="text-slate-500 text-xs mt-3 italic">Don&apos;t see your area? WhatsApp us — we cover all of Sharjah.</p>
            </div>
            <div>
              <h3 className="text-lg font-bold text-slate-900 mb-4 flex items-center gap-2">
                <MapPin className="h-5 w-5 text-cyan-500" aria-hidden="true" />
                Drop-off Points (JLT / Marina / JVC)
              </h3>
              <ul className="grid grid-cols-1 sm:grid-cols-2 gap-3 list-none" role="list">
                {DROP_OFF_POINTS.map((point) => (
                  <li key={point} className="flex items-center gap-3 bg-slate-50 border border-slate-200 rounded-xl px-4 py-3">
                    <CheckCircle className="h-4 w-4 text-cyan-500 shrink-0" aria-hidden="true" />
                    <span className="text-slate-800 font-medium text-sm">{point}</span>
                  </li>
                ))}
              </ul>
              <p className="text-slate-500 text-xs mt-3 italic">Exact drop-off confirmed at booking based on your tower.</p>
            </div>
          </div>
        </div>
      </section>

      {/* ── Pricing ──────────────────────────────────────────────────────── */}
      <section aria-labelledby="pricing-heading" className="py-14 sm:py-16 bg-slate-50">
        <div className="max-w-3xl mx-auto px-4 sm:px-6 lg:px-8">
          <div className="text-center mb-8">
            <p className="text-cyan-600 font-semibold text-sm uppercase tracking-widest mb-3">Transparent Pricing</p>
            <h2 id="pricing-heading" className="text-2xl sm:text-3xl font-extrabold text-slate-900 tracking-tight mb-3">
              JLT Carlift Monthly Rates
            </h2>
          </div>
          <div className="border border-slate-200 rounded-2xl overflow-hidden mb-6">
            <table className="w-full text-sm" aria-label="Carlift to JLT pricing by area and destination">
              <thead className="bg-slate-50 border-b border-slate-200">
                <tr>
                  <th className="text-left px-4 py-3 font-semibold text-slate-700">Pickup Area (Sharjah)</th>
                  <th className="text-center px-4 py-3 font-semibold text-slate-700">Destination</th>
                  <th className="text-right px-4 py-3 font-semibold text-slate-700">Monthly Price</th>
                </tr>
              </thead>
              <tbody>
                {PRICING_AREAS.map((row, i) => (
                  <tr key={`${row.area}-${row.note}`} className={i % 2 === 0 ? "bg-white" : "bg-slate-50/50"}>
                    <td className="px-4 py-3 text-slate-800 font-medium">{row.area}</td>
                    <td className="px-4 py-3 text-center text-slate-500 text-xs">{row.note}</td>
                    <td className="px-4 py-3 text-right font-extrabold text-cyan-600">{row.price}</td>
                  </tr>
                ))}
              </tbody>
            </table>
          </div>
          <div className="flex justify-center">
            <Button asChild variant="whatsapp" size="lg">
              <a href={whatsappHref} target="_blank" rel="noopener noreferrer">
                <MessageCircle className="h-5 w-5" aria-hidden="true" />
                Get Your Exact Price via WhatsApp
              </a>
            </Button>
          </div>
        </div>
      </section>

      {/* ── FAQ ─────────────────────────────────────────────────────────── */}
      <section aria-labelledby="faq-heading" className="py-14 sm:py-16 bg-white">
        <div className="max-w-3xl mx-auto px-4 sm:px-6 lg:px-8">
          <div className="text-center mb-10">
            <p className="text-cyan-600 font-semibold text-sm uppercase tracking-widest mb-3">FAQs</p>
            <h2 id="faq-heading" className="text-2xl sm:text-3xl font-extrabold text-slate-900 tracking-tight mb-3">
              Carlift Sharjah to JLT – Common Questions
            </h2>
          </div>
          <dl className="space-y-4">
            {PAGE_FAQS.map((faq, i) => (
              <details key={i} className="group border border-slate-200 rounded-2xl overflow-hidden bg-white">
                <summary className="flex items-center justify-between gap-4 cursor-pointer p-5 font-semibold text-slate-900 hover:bg-slate-50 transition-colors list-none [&::-webkit-details-marker]:hidden">
                  <dt className="text-left text-base">{faq.question}</dt>
                  <ChevronDown className="h-5 w-5 text-slate-400 shrink-0 transition-transform duration-300 group-open:rotate-180" aria-hidden="true" />
                </summary>
                <dd className="px-5 pb-5 text-slate-600 leading-relaxed text-sm border-t border-slate-100 pt-4">
                  {faq.answer}
                </dd>
              </details>
            ))}
          </dl>
        </div>
      </section>

      {/* ── Related pages ────────────────────────────────────────────────── */}
      <section aria-label="Related car lift pages" className="py-12 bg-slate-50">
        <div className="max-w-5xl mx-auto px-4 sm:px-6 lg:px-8">
          <h2 className="text-xl font-bold text-slate-900 mb-6 text-center">Related Car Lift Services</h2>
          <ul className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-4 gap-4 list-none" role="list">
            {[
              { href: "/car-lift-from-sharjah-to-business-bay", label: "Car Lift Sharjah to Business Bay", desc: "Full route guide & timings" },
              { href: "/carlift-sharjah-to-dubai-business-bay", label: "Carlift Sharjah to Dubai", desc: "Dubai-wide routes & monthly plans" },
              { href: "/carlift-sharjah-to-difc", label: "Carlift Sharjah to DIFC", desc: "Gate 1 & Gate 4 drop-off" },
              { href: "/ladies-car-lift-sharjah-to-dubai", label: "Ladies Car Lift Sharjah", desc: "Female driver, ladies-only" },
            ].map(({ href, label, desc }) => (
              <li key={href}>
                <Link href={href} className="group flex flex-col gap-2 p-5 border border-slate-200 hover:border-cyan-300 rounded-2xl hover:shadow-md transition-all h-full">
                  <span className="font-bold text-slate-900 group-hover:text-cyan-600 text-sm">{label}</span>
                  <span className="text-slate-500 text-xs flex-1">{desc}</span>
                  <span className="text-cyan-500 text-xs font-medium flex items-center gap-1 mt-2">
                    Learn more <ArrowRight className="h-3 w-3" aria-hidden="true" />
                  </span>
                </Link>
              </li>
            ))}
          </ul>
        </div>
      </section>

      {/* ── Final CTA ────────────────────────────────────────────────────── */}
      <section aria-label="Book your JLT carlift" className="py-14 bg-cyan-700">
        <div className="max-w-xl mx-auto px-4 text-center">
          <div className="flex items-center justify-center gap-0.5 mb-3" role="img" aria-label="4.9 out of 5 stars">
            {Array.from({ length: 5 }).map((_, i) => (
              <Star key={i} className="h-5 w-5 fill-amber-400 text-amber-400" aria-hidden="true" />
            ))}
          </div>
          <h2 className="text-white font-extrabold text-2xl sm:text-3xl mb-3">
            Book Your Daily JLT Carlift Today
          </h2>
          <p className="text-cyan-100 text-sm mb-6">
            {BUSINESS.reviewCount}+ daily riders trust Car Lift UAE. JLT seats fill fast — WhatsApp now to secure yours.
          </p>
          <div className="flex flex-col sm:flex-row gap-3 justify-center">
            <Button asChild size="xl" className="bg-white text-cyan-700 hover:bg-cyan-50 font-bold">
              <a href={whatsappHref} target="_blank" rel="noopener noreferrer" aria-label="Book carlift Sharjah to JLT">
                <MessageCircle className="h-5 w-5" aria-hidden="true" />
                WhatsApp – Book Now
              </a>
            </Button>
            <Button asChild size="xl" className="border-2 border-white/40 bg-white/10 text-white hover:bg-white/20">
              <a href={phoneHref}>
                <Phone className="h-5 w-5" aria-hidden="true" />
                Call {BUSINESS.phone}
              </a>
            </Button>
          </div>
        </div>
      </section>
    </>
  );
}
