import type { Metadata } from "next";
import Link from "next/link";
import {
  Car,
  Clock,
  DollarSign,
  MapPin,
  CheckCircle,
  MessageCircle,
  Phone,
  ArrowRight,
  ChevronDown,
  Users,
  Star,
  Shield,
} from "lucide-react";
import { Card, CardContent } from "@/components/ui/card";
import { Button } from "@/components/ui/button";
import Breadcrumb from "@/components/sections/breadcrumb";
import SchemaScript from "@/components/sections/schema-script";
import {
  localBusinessSchema,
  faqSchema,
  breadcrumbSchema,
  serviceSchema,
  primaryImageOfPageSchema,
} from "@/lib/schema";
import { BUSINESS, formatWhatsAppHref, formatPhoneHref } from "@/lib/utils";

export const revalidate = 86400;

export const metadata: Metadata = {
  title: "Carlift Sharjah to DIFC – AED 350/Month | +971 50 725 5334",
  description:
    "Daily carlift from Sharjah to DIFC (Dubai International Financial Centre) from AED 350/month. Salik included, GPS-tracked, 4.9★ rated. Ladies option. WhatsApp +971 50 725 5334.",
  keywords:
    "sharjah to difc, carlift sharjah to difc, car lift sharjah to difc, difc to sharjah carlift, sharjah difc car lift monthly",
  alternates: {
    canonical: "https://www.carliftuae.com/carlift-sharjah-to-difc",
  },
  openGraph: {
    title: "Carlift Sharjah to DIFC – AED 350/Month | +971 50 725 5334",
    description:
      "Daily carlift Sharjah to DIFC from AED 350/month. Gate 1/Gate 4 drop-off. Salik included, GPS-tracked. Ladies option. WhatsApp +971 50 725 5334.",
    // OG image generated by src/app/carlift-sharjah-to-difc/opengraph-image.tsx
  },
};

const PAGE_FAQS = [
  {
    question: "How much does a carlift from Sharjah to DIFC cost per month?",
    answer:
      "Monthly carlift from Sharjah to DIFC starts at AED 350/month from Al Nahda, Sharjah. Areas farther from Dubai such as Muweilah and University City are AED 380–420/month. All prices include Salik toll on Sheikh Zayed Road — no hidden charges.",
  },
  {
    question: "Where does the carlift drop off in DIFC?",
    answer:
      "We drop off at DIFC Gate 1 (main entrance near The Gate building), DIFC Gate 4 (ICD Brookfield Place side), The Gate Precinct, and other major DIFC towers on request. Confirm your exact building when you book via WhatsApp.",
  },
  {
    question: "What time does the carlift from Sharjah to DIFC depart?",
    answer:
      "Morning departures from Sharjah: 6:30 AM, 7:00 AM, 7:30 AM, and 8:00 AM. Evening return from DIFC to Sharjah: 5:00 PM, 5:30 PM, 6:00 PM, and 6:30 PM. You choose your preferred timing when you book.",
  },
  {
    question: "How long is the journey from Sharjah to DIFC?",
    answer:
      "The journey from Al Nahda, Sharjah to DIFC takes approximately 45–70 minutes via Sheikh Zayed Road (E11). The 6:30 AM departure is fastest at 45–55 minutes. The 7:30–8:00 AM slots take 60–70 minutes during peak traffic.",
  },
  {
    question: "Which Sharjah areas are covered for the DIFC carlift?",
    answer:
      "We pick up from Al Nahda, Al Taawun, Al Khan, Al Majaz, Muweilah, University City, Al Zahia, Rolla, Al Qasimia, and all other Sharjah areas. WhatsApp us your building address for a quick confirmation.",
  },
  {
    question: "Is there a ladies-only carlift from Sharjah to DIFC?",
    answer:
      "Yes. A ladies-only carlift from Sharjah to DIFC is available with a female driver on request, or a ladies-only vehicle with female passengers only. It is the same route, same price — just a private women-only ride.",
  },
];

const TIMINGS = [
  { label: "Sharjah → DIFC (Morning)", times: ["6:30 AM", "7:00 AM", "7:30 AM", "8:00 AM"], color: "bg-violet-700" },
  { label: "DIFC → Sharjah (Evening)", times: ["5:00 PM", "5:30 PM", "6:00 PM", "6:30 PM"], color: "bg-slate-800" },
];

const PICKUP_AREAS = [
  "Al Nahda (Sharjah)", "Al Taawun", "Al Khan", "Al Majaz",
  "Muweilah", "University City", "Al Zahia", "Rolla Area",
  "Al Qasimia", "Industrial Area 1–3",
];

const DROP_OFF_POINTS = [
  "DIFC Gate 1 – The Gate", "DIFC Gate 4 – ICD Brookfield",
  "The Gate Precinct", "Central Park Towers",
  "Currency House", "Emirates Financial Towers",
  "Index Tower", "Burj Daman",
];

const PRICING_AREAS = [
  { area: "Al Nahda", price: "AED 350", note: "Closest to Dubai" },
  { area: "Al Taawun / Al Khan", price: "AED 370", note: "" },
  { area: "Al Majaz / Rolla", price: "AED 380", note: "" },
  { area: "Muweilah", price: "AED 400", note: "" },
  { area: "University City / Al Zahia", price: "AED 420+", note: "Farther zone" },
];

const COST_COMPARISON = [
  { label: "DIFC parking (AED 25–40/day × 26 days)", amount: "AED 650–1,040", highlight: false },
  { label: "Fuel Sharjah–DIFC–Sharjah monthly", amount: "AED 520", highlight: false },
  { label: "Salik gates (SZR toll)", amount: "AED 338", highlight: false },
  { label: "Total driving cost", amount: "AED 1,508–1,898", highlight: true },
  { label: "Car Lift UAE monthly (Al Nahda)", amount: "AED 350", highlight: true },
];

export default function CarliftSharjahToDifcPage() {
  const whatsappHref = formatWhatsAppHref(
    BUSINESS.whatsapp,
    "Hi! I want to book carlift from Sharjah to DIFC."
  );
  const phoneHref = formatPhoneHref(BUSINESS.phone);

  const schemas = [
    localBusinessSchema(),
    serviceSchema({
      name: "Carlift Sharjah to DIFC",
      description:
        "Daily carlift from Sharjah to Dubai International Financial Centre (DIFC). Monthly packages from AED 350/month. Salik included, GPS-tracked.",
      url: "/carlift-sharjah-to-difc",
      price: "350",
    }),
    faqSchema(PAGE_FAQS),
    breadcrumbSchema([
      { name: "Home", url: "/" },
      { name: "Carlift Sharjah to DIFC", url: "/carlift-sharjah-to-difc" },
    ]),
    primaryImageOfPageSchema({
      imageUrl: "/images/routes/carlift-sheikh-zayed-road-dropoff.webp",
      pageUrl: "/carlift-sharjah-to-difc",
      caption: "Carlift drop-off near DIFC Dubai – Sheikh Zayed Road daily commute",
    }),
  ];

  return (
    <>
      <SchemaScript schema={schemas} />

      {/* ── Hero ─────────────────────────────────────────────────────────── */}
      <section
        aria-labelledby="hero-heading"
        className="relative overflow-hidden py-16 sm:py-20"
        style={{ background: "linear-gradient(135deg, #2e1065 0%, #4c1d95 50%, #1e1b4b 100%)" }}
      >
        <div
          className="absolute inset-0 opacity-[0.04] pointer-events-none"
          style={{ backgroundImage: "radial-gradient(circle, rgba(255,255,255,0.8) 1px, transparent 1px)", backgroundSize: "28px 28px" }}
          aria-hidden="true"
        />
        <div className="relative z-10 max-w-5xl mx-auto px-4 sm:px-6 lg:px-8">
          <Breadcrumb
            items={[{ label: "Home", href: "/" }, { label: "Carlift Sharjah to DIFC" }]}
            className="mb-6 [&_*]:text-violet-400 [&_a]:text-violet-300 [&_a:hover]:text-white"
          />
          <div className="flex flex-col lg:flex-row lg:items-start lg:justify-between gap-10">
            <div className="flex-1">
              <div className="inline-flex items-center gap-2 bg-violet-500/20 border border-violet-400/30 rounded-full px-4 py-1.5 text-sm text-violet-300 font-semibold mb-5">
                <Car className="h-4 w-4" aria-hidden="true" />
                From AED 350/month · Salik Included · Gate 1 &amp; Gate 4 Drop-off
              </div>
              <h1 id="hero-heading" className="text-3xl sm:text-4xl lg:text-5xl font-extrabold text-white tracking-tight leading-tight mb-4">
                Carlift Sharjah to DIFC<br className="hidden sm:block" /> Daily Commute
              </h1>
              <p className="text-violet-100 text-base sm:text-lg leading-relaxed mb-3 max-w-xl">
                Daily carlift from all major Sharjah areas straight to Dubai International Financial Centre.
                Drop-off at Gate 1, Gate 4, ICD Brookfield Place, and all major DIFC towers.
              </p>
              <p className="text-violet-200/80 text-sm leading-relaxed mb-6 max-w-xl">
                DIFC parking alone costs AED 650–1,040/month. Switch to our monthly carlift from AED 350 and arrive stress-free via Sheikh Zayed Road.
              </p>
              <ul className="grid grid-cols-2 sm:grid-cols-4 gap-3 mb-8" role="list" aria-label="Key route stats">
                {[
                  { icon: DollarSign, label: "From AED 350", sub: "/month" },
                  { icon: Clock, label: "45–70 min", sub: "Journey Time" },
                  { icon: Car, label: "4 Timings", sub: "Morning Daily" },
                  { icon: Users, label: "SZR Route", sub: "Sheikh Zayed Rd" },
                ].map(({ icon: Icon, label, sub }) => (
                  <li key={sub} className="bg-white/10 border border-white/15 rounded-xl p-4 text-center">
                    <Icon className="h-5 w-5 text-violet-400 mx-auto mb-1.5" aria-hidden="true" />
                    <p className="text-white font-extrabold text-base leading-none">{label}</p>
                    <p className="text-violet-200/70 text-xs mt-1">{sub}</p>
                  </li>
                ))}
              </ul>
              <div className="flex flex-col sm:flex-row gap-3">
                <Button asChild variant="whatsapp" size="lg">
                  <a href={whatsappHref} target="_blank" rel="noopener noreferrer" aria-label="Book carlift Sharjah to DIFC via WhatsApp">
                    <MessageCircle className="h-5 w-5" aria-hidden="true" />
                    Book via WhatsApp
                  </a>
                </Button>
                <Button asChild size="lg" className="border-2 border-white/30 bg-white/10 text-white hover:bg-white/20">
                  <a href={phoneHref} aria-label="Call Car Lift UAE">
                    <Phone className="h-5 w-5" aria-hidden="true" />
                    Call {BUSINESS.phone}
                  </a>
                </Button>
              </div>
            </div>
            <aside className="lg:w-72 bg-white/10 border border-white/15 backdrop-blur-sm rounded-2xl p-6 shrink-0" aria-label="What is included">
              <p className="text-white font-bold text-base mb-4 flex items-center gap-2">
                <CheckCircle className="h-5 w-5 text-violet-400" aria-hidden="true" />
                What&apos;s Included
              </p>
              <ul className="space-y-3" role="list">
                {[
                  "Morning & evening rides",
                  "Salik tolls included",
                  "DIFC Gate 1 / Gate 4 drop-off",
                  "GPS-tracked vehicle",
                  "Verified UAE driver",
                  "Air-conditioned vehicle",
                  "WhatsApp support 24/7",
                  "Ladies-only option",
                ].map((item) => (
                  <li key={item} className="flex items-center gap-2.5">
                    <CheckCircle className="h-4 w-4 text-violet-400 shrink-0" aria-hidden="true" />
                    <span className="text-violet-100 text-sm">{item}</span>
                  </li>
                ))}
              </ul>
            </aside>
          </div>
        </div>
      </section>

      {/* ── Cost Comparison ──────────────────────────────────────────────── */}
      <section aria-labelledby="cost-heading" className="py-14 sm:py-16 bg-white">
        <div className="max-w-5xl mx-auto px-4 sm:px-6 lg:px-8">
          <div className="text-center mb-10">
            <p className="text-violet-600 font-semibold text-sm uppercase tracking-widest mb-3">Why Car Lift Wins</p>
            <h2 id="cost-heading" className="text-2xl sm:text-3xl font-extrabold text-slate-900 tracking-tight mb-3">
              DIFC Parking Alone Costs More Than Our Monthly Carlift
            </h2>
          </div>
          <div className="max-w-xl mx-auto space-y-3 mb-8">
            {COST_COMPARISON.map((row) => (
              <div key={row.label} className={`flex items-center justify-between gap-4 rounded-xl px-5 py-3.5 border ${row.highlight ? "bg-violet-50 border-violet-200 font-bold" : "bg-slate-50 border-slate-200"}`}>
                <span className={`text-sm ${row.highlight ? "text-violet-900" : "text-slate-700"}`}>{row.label}</span>
                <span className={`text-sm font-bold shrink-0 ${row.highlight ? "text-violet-600" : "text-slate-600"}`}>{row.amount}</span>
              </div>
            ))}
          </div>
          <div className="text-center">
            <Button asChild variant="whatsapp" size="default">
              <a href={whatsappHref} target="_blank" rel="noopener noreferrer">
                <MessageCircle className="h-4 w-4" aria-hidden="true" />
                Save AED 1,100+/Month – Book Now
              </a>
            </Button>
          </div>
        </div>
      </section>

      {/* ── Timings ─────────────────────────────────────────────────────── */}
      <section aria-labelledby="timings-heading" className="py-14 sm:py-16 bg-slate-50">
        <div className="max-w-5xl mx-auto px-4 sm:px-6 lg:px-8">
          <div className="text-center mb-10">
            <p className="text-violet-600 font-semibold text-sm uppercase tracking-widest mb-3">Daily Schedule</p>
            <h2 id="timings-heading" className="text-2xl sm:text-3xl font-extrabold text-slate-900 tracking-tight mb-3">
              Sharjah to DIFC Carlift Timings
            </h2>
          </div>
          <div className="grid grid-cols-1 sm:grid-cols-2 gap-6">
            {TIMINGS.map((t) => (
              <Card key={t.label} className="border-slate-200">
                <CardContent className="p-6 pt-6">
                  <div className="flex items-center gap-3 mb-5">
                    <div className={`w-9 h-9 rounded-xl ${t.color} flex items-center justify-center shrink-0`}>
                      <Clock className="h-5 w-5 text-white" aria-hidden="true" />
                    </div>
                    <h3 className="font-bold text-slate-900 text-sm">{t.label}</h3>
                  </div>
                  <div className="grid grid-cols-2 gap-3">
                    {t.times.map((time) => (
                      <div key={time} className="bg-slate-50 border border-slate-200 rounded-xl p-3 text-center">
                        <p className="font-extrabold text-slate-900 text-xl">{time}</p>
                      </div>
                    ))}
                  </div>
                </CardContent>
              </Card>
            ))}
          </div>
        </div>
      </section>

      {/* ── Pickup & Drop-off ────────────────────────────────────────────── */}
      <section aria-labelledby="pickup-heading" className="py-14 sm:py-16 bg-white">
        <div className="max-w-5xl mx-auto px-4 sm:px-6 lg:px-8">
          <div className="text-center mb-10">
            <p className="text-violet-600 font-semibold text-sm uppercase tracking-widest mb-3">Route Coverage</p>
            <h2 id="pickup-heading" className="text-2xl sm:text-3xl font-extrabold text-slate-900 tracking-tight mb-3">
              Pickup in Sharjah · Drop-off in DIFC
            </h2>
          </div>
          <div className="grid grid-cols-1 lg:grid-cols-2 gap-8">
            <div>
              <h3 className="text-lg font-bold text-slate-900 mb-4 flex items-center gap-2">
                <MapPin className="h-5 w-5 text-violet-500" aria-hidden="true" />
                Pickup Areas (Sharjah)
              </h3>
              <ul className="grid grid-cols-1 sm:grid-cols-2 gap-3 list-none" role="list">
                {PICKUP_AREAS.map((area) => (
                  <li key={area} className="flex items-center gap-3 bg-slate-50 border border-slate-200 rounded-xl px-4 py-3">
                    <CheckCircle className="h-4 w-4 text-emerald-500 shrink-0" aria-hidden="true" />
                    <span className="text-slate-800 font-medium text-sm">{area}</span>
                  </li>
                ))}
              </ul>
            </div>
            <div>
              <h3 className="text-lg font-bold text-slate-900 mb-4 flex items-center gap-2">
                <MapPin className="h-5 w-5 text-violet-500" aria-hidden="true" />
                Drop-off Points (DIFC)
              </h3>
              <ul className="grid grid-cols-1 sm:grid-cols-2 gap-3 list-none" role="list">
                {DROP_OFF_POINTS.map((point) => (
                  <li key={point} className="flex items-center gap-3 bg-slate-50 border border-slate-200 rounded-xl px-4 py-3">
                    <CheckCircle className="h-4 w-4 text-violet-500 shrink-0" aria-hidden="true" />
                    <span className="text-slate-800 font-medium text-sm">{point}</span>
                  </li>
                ))}
              </ul>
              <p className="text-slate-500 text-xs mt-3 italic">Exact drop-off point confirmed at booking.</p>
            </div>
          </div>
        </div>
      </section>

      {/* ── Pricing ──────────────────────────────────────────────────────── */}
      <section aria-labelledby="pricing-heading" className="py-14 sm:py-16 bg-slate-50">
        <div className="max-w-3xl mx-auto px-4 sm:px-6 lg:px-8">
          <div className="text-center mb-8">
            <p className="text-violet-600 font-semibold text-sm uppercase tracking-widest mb-3">Transparent Pricing</p>
            <h2 id="pricing-heading" className="text-2xl sm:text-3xl font-extrabold text-slate-900 tracking-tight mb-3">
              DIFC Carlift Monthly Rates
            </h2>
          </div>
          <div className="border border-slate-200 rounded-2xl overflow-hidden mb-6">
            <table className="w-full text-sm" aria-label="Carlift to DIFC pricing by Sharjah area">
              <thead className="bg-slate-50 border-b border-slate-200">
                <tr>
                  <th className="text-left px-4 py-3 font-semibold text-slate-700">Pickup Area (Sharjah)</th>
                  <th className="text-right px-4 py-3 font-semibold text-slate-700">Monthly Price</th>
                </tr>
              </thead>
              <tbody>
                {PRICING_AREAS.map((row, i) => (
                  <tr key={row.area} className={i % 2 === 0 ? "bg-white" : "bg-slate-50/50"}>
                    <td className="px-4 py-3 text-slate-800 font-medium">
                      {row.area}
                      {row.note && <span className="ml-2 text-xs text-slate-400">({row.note})</span>}
                    </td>
                    <td className="px-4 py-3 text-right font-extrabold text-violet-600">{row.price}</td>
                  </tr>
                ))}
              </tbody>
            </table>
          </div>
          <div className="flex justify-center">
            <Button asChild variant="whatsapp" size="lg">
              <a href={whatsappHref} target="_blank" rel="noopener noreferrer">
                <MessageCircle className="h-5 w-5" aria-hidden="true" />
                Get Your Exact Price via WhatsApp
              </a>
            </Button>
          </div>
        </div>
      </section>

      {/* ── FAQ ─────────────────────────────────────────────────────────── */}
      <section aria-labelledby="faq-heading" className="py-14 sm:py-16 bg-white">
        <div className="max-w-3xl mx-auto px-4 sm:px-6 lg:px-8">
          <div className="text-center mb-10">
            <p className="text-violet-600 font-semibold text-sm uppercase tracking-widest mb-3">FAQs</p>
            <h2 id="faq-heading" className="text-2xl sm:text-3xl font-extrabold text-slate-900 tracking-tight mb-3">
              Carlift Sharjah to DIFC – Common Questions
            </h2>
          </div>
          <dl className="space-y-4">
            {PAGE_FAQS.map((faq, i) => (
              <details key={i} className="group border border-slate-200 rounded-2xl overflow-hidden bg-white">
                <summary className="flex items-center justify-between gap-4 cursor-pointer p-5 font-semibold text-slate-900 hover:bg-slate-50 transition-colors list-none [&::-webkit-details-marker]:hidden">
                  <dt className="text-left text-base">{faq.question}</dt>
                  <ChevronDown className="h-5 w-5 text-slate-400 shrink-0 transition-transform duration-300 group-open:rotate-180" aria-hidden="true" />
                </summary>
                <dd className="px-5 pb-5 text-slate-600 leading-relaxed text-sm border-t border-slate-100 pt-4">
                  {faq.answer}
                </dd>
              </details>
            ))}
          </dl>
        </div>
      </section>

      {/* ── Related pages ────────────────────────────────────────────────── */}
      <section aria-label="Related car lift pages" className="py-12 bg-slate-50">
        <div className="max-w-5xl mx-auto px-4 sm:px-6 lg:px-8">
          <h2 className="text-xl font-bold text-slate-900 mb-6 text-center">Related Car Lift Services</h2>
          <ul className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-4 gap-4 list-none" role="list">
            {[
              { href: "/car-lift-from-sharjah-to-business-bay", label: "Car Lift Sharjah to Business Bay", desc: "Full route guide & timings" },
              { href: "/carlift-sharjah-to-dubai-business-bay", label: "Carlift Sharjah to Dubai", desc: "Dubai-wide routes & pricing" },
              { href: "/carlift-sharjah-to-jlt", label: "Carlift Sharjah to JLT", desc: "JLT, Dubai Marina & JVC" },
              { href: "/ladies-car-lift-sharjah-to-dubai", label: "Ladies Car Lift Sharjah", desc: "Female driver option" },
            ].map(({ href, label, desc }) => (
              <li key={href}>
                <Link href={href} className="group flex flex-col gap-2 p-5 border border-slate-200 hover:border-violet-300 rounded-2xl hover:shadow-md transition-all h-full">
                  <span className="font-bold text-slate-900 group-hover:text-violet-600 text-sm">{label}</span>
                  <span className="text-slate-500 text-xs flex-1">{desc}</span>
                  <span className="text-violet-500 text-xs font-medium flex items-center gap-1 mt-2">
                    Learn more <ArrowRight className="h-3 w-3" aria-hidden="true" />
                  </span>
                </Link>
              </li>
            ))}
          </ul>
        </div>
      </section>

      {/* ── Final CTA ────────────────────────────────────────────────────── */}
      <section aria-label="Book your DIFC carlift" className="py-14 bg-violet-700">
        <div className="max-w-xl mx-auto px-4 text-center">
          <div className="flex items-center justify-center gap-0.5 mb-3" role="img" aria-label="4.9 out of 5 stars">
            {Array.from({ length: 5 }).map((_, i) => (
              <Star key={i} className="h-5 w-5 fill-amber-400 text-amber-400" aria-hidden="true" />
            ))}
          </div>
          <h2 className="text-white font-extrabold text-2xl sm:text-3xl mb-3">
            Book Your Daily DIFC Carlift Today
          </h2>
          <p className="text-violet-100 text-sm mb-6">
            {BUSINESS.reviewCount}+ daily riders trust Car Lift UAE. Seats fill fast — WhatsApp now to secure yours.
          </p>
          <div className="flex flex-col sm:flex-row gap-3 justify-center">
            <Button asChild size="xl" className="bg-white text-violet-700 hover:bg-violet-50 font-bold">
              <a href={whatsappHref} target="_blank" rel="noopener noreferrer" aria-label="Book carlift Sharjah to DIFC">
                <MessageCircle className="h-5 w-5" aria-hidden="true" />
                WhatsApp – Book Now
              </a>
            </Button>
            <Button asChild size="xl" className="border-2 border-white/40 bg-white/10 text-white hover:bg-white/20">
              <a href={phoneHref}>
                <Phone className="h-5 w-5" aria-hidden="true" />
                Call {BUSINESS.phone}
              </a>
            </Button>
          </div>
        </div>
      </section>
    </>
  );
}
