import type { Metadata } from "next";
import HeroSection from "@/components/sections/hero-section";
import ServicesSection from "@/components/sections/services-section";
import WhyChooseSection from "@/components/sections/why-choose-section";
import RouteSection from "@/components/sections/route-section";
import PricingSection from "@/components/sections/pricing-section";
import FaqSection from "@/components/sections/faq-section";
import CtaBanner from "@/components/sections/cta-banner";
import SchemaScript from "@/components/sections/schema-script";
import { localBusinessSchema, faqSchema, speakableSchema, primaryImageOfPageSchema } from "@/lib/schema";
import { FAQS } from "@/data/faqs";

export const metadata: Metadata = {
  title: "Quick Car Lift Service UAE – Dubai, Abu Dhabi, Sharjah & Ajman | +971 54 330 8261",
  description:
    "Quick Car Lift Service UAE: luxury car lift covering Dubai ↔ Abu Dhabi (AED 100 sharing / AED 170 private), Abu Dhabi ↔ Sharjah & Ajman (AED 130 sharing / AED 200 private). Available 24/7. Call or WhatsApp +971 54 330 8261.",
  keywords:
    "car lift uae, carpool uae, car lift dubai abu dhabi, car lift abu dhabi sharjah, car lift abu dhabi ajman, Quick Car Lift Service UAE, airport transfer uae",
  alternates: { canonical: "https://www.carliftuae.com/" },
  openGraph: {
    title: "Quick Car Lift Service UAE – Dubai, Abu Dhabi, Sharjah & Ajman | +971 54 330 8261",
    description:
      "Luxury car lift UAE. Dubai ↔ Abu Dhabi from AED 100 sharing / AED 170 private. Abu Dhabi ↔ Sharjah/Ajman from AED 130 sharing / AED 200 private. Available 24/7. Call or WhatsApp +971 54 330 8261.",
    // OG image generated by src/app/opengraph-image.tsx
  },
};

export const revalidate = 86400;

const HOME_FAQS = FAQS.slice(0, 10);

export default function HomePage() {
  return (
    <>
      <SchemaScript
        schema={[
          localBusinessSchema(),
          faqSchema(HOME_FAQS),
          speakableSchema([".hero-heading", ".hero-description"]),
          primaryImageOfPageSchema({
            imageUrl: "/images/hero/carlift-uae-daily-commuters-interior.webp",
            pageUrl: "/",
            caption: "Quick Car Lift Service UAE – comfortable inter-emirate car lift rides across Dubai, Abu Dhabi, Sharjah and Ajman",
            width: 1920,
            height: 1080,
          }),
        ]}
      />
      <HeroSection />
      <ServicesSection />
      <WhyChooseSection />
      <RouteSection />
      <PricingSection />
      <FaqSection />
      <CtaBanner />
    </>
  );
}
