import type { Metadata } from "next";
import HeroSection from "@/components/sections/hero-section";
import ServicesSection from "@/components/sections/services-section";
import WhyChooseSection from "@/components/sections/why-choose-section";
import RouteSection from "@/components/sections/route-section";
import PricingSection from "@/components/sections/pricing-section";
import TestimonialsSection from "@/components/sections/testimonials-section";
import FaqSection from "@/components/sections/faq-section";
import CtaBanner from "@/components/sections/cta-banner";
import SchemaScript from "@/components/sections/schema-script";
import { localBusinessSchema, faqSchema, speakableSchema, primaryImageOfPageSchema } from "@/lib/schema";
import { FAQS } from "@/data/faqs";

export const metadata: Metadata = {
  title: "MJ Car Lift Service – Dubai, Abu Dhabi, Sharjah & Ajman | +971 56 228 6455",
  description:
    "MJ Car Lift Service: reliable car lift and carpool rides covering Dubai ↔ Abu Dhabi (AED 200), Abu Dhabi ↔ Sharjah (AED 280), Abu Dhabi ↔ Ajman (AED 300). Airport transfers available. Call or WhatsApp +971 56 228 6455.",
  keywords:
    "car lift uae, carpool uae, car lift dubai abu dhabi, car lift abu dhabi sharjah, car lift abu dhabi ajman, MJ car lift service, airport transfer uae",
  alternates: { canonical: "https://www.carliftuae.com/" },
  openGraph: {
    title: "MJ Car Lift Service – Dubai, Abu Dhabi, Sharjah & Ajman | +971 56 228 6455",
    description:
      "Car lift and carpool service on confirmed inter-emirate routes. Dubai ↔ Abu Dhabi from AED 200. Airport transfers available. Call or WhatsApp +971 56 228 6455.",
    // OG image generated by src/app/opengraph-image.tsx
  },
};

export const revalidate = 86400;

const HOME_FAQS = FAQS.slice(0, 10);

export default function HomePage() {
  return (
    <>
      <SchemaScript
        schema={[
          localBusinessSchema(),
          faqSchema(HOME_FAQS),
          speakableSchema([".hero-heading", ".hero-description"]),
          primaryImageOfPageSchema({
            imageUrl: "/images/hero/carlift-uae-daily-commuters-interior.webp",
            pageUrl: "/",
            caption: "MJ Car Lift Service – comfortable inter-emirate car lift rides across Dubai, Abu Dhabi, Sharjah and Ajman",
            width: 1920,
            height: 1080,
          }),
        ]}
      />
      <HeroSection />
      <ServicesSection />
      <WhyChooseSection />
      <RouteSection />
      <PricingSection />
      <TestimonialsSection />
      <FaqSection />
      <CtaBanner />
    </>
  );
}
