import type { Metadata } from "next";
import HeroSection from "@/components/sections/hero-section";
import ServicesSection from "@/components/sections/services-section";
import WhyChooseSection from "@/components/sections/why-choose-section";
import RouteSection from "@/components/sections/route-section";
import PricingSection from "@/components/sections/pricing-section";
import TestimonialsSection from "@/components/sections/testimonials-section";
import FaqSection from "@/components/sections/faq-section";
import CtaBanner from "@/components/sections/cta-banner";
import SchemaScript from "@/components/sections/schema-script";
import { localBusinessSchema, faqSchema, speakableSchema, primaryImageOfPageSchema } from "@/lib/schema";
import { FAQS } from "@/data/faqs";

export const metadata: Metadata = {
  title: "Carlift Sharjah to Business Bay – AED 300/Month | +971 56 228 6455",
  description:
    "Carlift Sharjah to Business Bay from AED 300/month. Salik included, GPS-tracked, 4.9★ rated by 247+ riders. Ladies car lift available. WhatsApp +971 56 228 6455 – confirm seat in 60 seconds.",
  keywords:
    "carlift uae, car lift uae, carlift sharjah to business bay, car lift sharjah to business bay, car lift sharjah, car lift service uae, daily car lift sharjah, monthly car lift dubai, car lift ajman, ladies car lift uae, carlift service",
  alternates: { canonical: "https://www.carliftuae.com/" },
  openGraph: {
    title: "Carlift Sharjah to Business Bay – AED 300/Month | +971 56 228 6455",
    description:
      "500+ professionals trust Car Lift UAE daily. Sharjah → Business Bay from AED 300/month. Salik included, GPS-tracked, ladies option. WhatsApp +971 56 228 6455.",
    // OG image generated by src/app/opengraph-image.tsx
  },
};

export const revalidate = 86400;

const HOME_FAQS = FAQS.slice(0, 10);

export default function HomePage() {
  return (
    <>
      <SchemaScript
        schema={[
          localBusinessSchema(),
          faqSchema(HOME_FAQS),
          speakableSchema([".hero-heading", ".hero-description"]),
          primaryImageOfPageSchema({
            imageUrl: "/images/hero/carlift-uae-daily-commuters-interior.webp",
            pageUrl: "/",
            caption: "Daily car lift commuters sharing a comfortable ride from Sharjah to Business Bay Dubai – Car Lift UAE",
            width: 1920,
            height: 1080,
          }),
        ]}
      />
      <HeroSection />
      <ServicesSection />
      <WhyChooseSection />
      <RouteSection />
      <PricingSection />
      <TestimonialsSection />
      <FaqSection />
      <CtaBanner />
    </>
  );
}
