import type { Metadata } from "next";
import Link from "next/link";
import {
  Car,
  Clock,
  DollarSign,
  MapPin,
  CheckCircle,
  MessageCircle,
  Phone,
  ArrowRight,
  ChevronDown,
  Users,
  Star,
  Shield,
} from "lucide-react";
import { Card, CardContent } from "@/components/ui/card";
import { Button } from "@/components/ui/button";
import Breadcrumb from "@/components/sections/breadcrumb";
import SchemaScript from "@/components/sections/schema-script";
import {
  localBusinessSchema,
  faqSchema,
  breadcrumbSchema,
  serviceSchema,
  primaryImageOfPageSchema,
} from "@/lib/schema";
import { BUSINESS, formatWhatsAppHref, formatPhoneHref } from "@/lib/utils";

export const revalidate = 86400;

export const metadata: Metadata = {
  title: "Ladies Car Lift Sharjah to Dubai – Female Driver | +971 50 725 5334",
  description:
    "Ladies-only car lift from Sharjah to Dubai from AED 300/month. Verified female drivers, ladies-only vehicles, GPS-tracked, 4.9★ rated. Safe daily commute. WhatsApp +971 50 725 5334.",
  keywords:
    "car lift for ladies in sharjah, ladies car lift sharjah to dubai, ladies car lift sharjah, car lift for ladies in dubai, female car lift uae, ladies only car lift sharjah",
  alternates: {
    canonical: "https://www.carliftuae.com/ladies-car-lift-sharjah-to-dubai",
  },
  openGraph: {
    title: "Ladies Car Lift Sharjah to Dubai – Female Driver | +971 50 725 5334",
    description:
      "Ladies-only car lift from Sharjah to Dubai from AED 300/month. Verified female drivers, GPS-tracked, 4.9★ rated. WhatsApp +971 50 725 5334.",
    // OG image generated by src/app/ladies-car-lift-sharjah-to-dubai/opengraph-image.tsx
  },
};

const PAGE_FAQS = [
  {
    question: "Is there a ladies-only car lift from Sharjah to Dubai?",
    answer:
      "Yes. Car Lift UAE offers a dedicated ladies-only car lift from Sharjah to Dubai with two options: a vehicle with a verified female driver, or a ladies-only vehicle with a male driver but exclusively female passengers. Both options provide a safe, comfortable daily commute from all major Sharjah areas.",
  },
  {
    question: "How much does the ladies car lift from Sharjah to Dubai cost?",
    answer:
      "Ladies car lift from Sharjah to Dubai Business Bay, DIFC, JLT, and other destinations starts from AED 300/month from Al Nahda, Sharjah. The price is the same as the standard service — no extra charge for the ladies-only option. Salik tolls are fully included.",
  },
  {
    question: "How do I know the driver is verified and safe?",
    answer:
      "All Car Lift UAE drivers hold a valid UAE driving licence and have undergone background checks. For our ladies service, female drivers hold current RTA-approved licences. You can share your live location with a family member directly from the vehicle, and our 24/7 WhatsApp support is always available during your trip.",
  },
  {
    question: "Which destinations does the ladies car lift cover?",
    answer:
      "We cover all major Dubai business destinations: Business Bay, DIFC, JLT (Jumeirah Lakes Towers), Dubai Marina, Al Barsha, JVC (Jumeirah Village Circle), Deira, and more. WhatsApp us with your destination and we will confirm availability same day.",
  },
  {
    question: "What pickup areas in Sharjah does the ladies car lift serve?",
    answer:
      "We pick up from all major Sharjah areas including Al Nahda, Al Taawun, Al Khan, Al Majaz, Muweilah, University City, Al Zahia, Rolla, and more. WhatsApp your building name and we will confirm your nearest pickup point.",
  },
  {
    question: "What safety features does the ladies car lift have?",
    answer:
      "Every ladies car lift vehicle is GPS-tracked in real time, so you can share your live location with family. Vehicles have an in-vehicle camera for security, and the WhatsApp support line operates 24/7. You can also add an emergency contact to your booking who receives trip start and end notifications.",
  },
];

const PICKUP_AREAS = [
  "Al Nahda (Sharjah)", "Al Taawun", "Al Khan", "Al Majaz",
  "Muweilah", "University City", "Al Zahia", "Rolla Area",
  "Al Qasimia", "Al Qusais",
];

const DESTINATIONS = [
  { area: "Business Bay", time: "40–65 min", price: "AED 300/mo" },
  { area: "DIFC", time: "45–70 min", price: "AED 350/mo" },
  { area: "JLT", time: "55–75 min", price: "AED 380/mo" },
  { area: "Dubai Marina", time: "60–80 min", price: "AED 400/mo" },
  { area: "Al Barsha", time: "50–70 min", price: "AED 380/mo" },
  { area: "JVC", time: "55–75 min", price: "AED 370/mo" },
];

const SAFETY_FEATURES = [
  { title: "Verified Female Driver", desc: "All female drivers hold valid UAE RTA licences and pass our background check." },
  { title: "Ladies-Only Passengers", desc: "Choose a vehicle where every seat is occupied by a female commuter only." },
  { title: "Live Location Sharing", desc: "Share your GPS-tracked route with family in real time during each trip." },
  { title: "In-Vehicle Camera", desc: "All ladies service vehicles are fitted with interior cameras for added security." },
  { title: "Emergency Contact", desc: "Add a contact who receives SMS notifications when your trip starts and ends." },
  { title: "24/7 WhatsApp Support", desc: "Our support team is available around the clock — message us any time." },
];

export default function LadiesCarLiftSharjahToDubaiPage() {
  const whatsappHref = formatWhatsAppHref(
    BUSINESS.whatsapp,
    "Hi! I want to book ladies car lift from Sharjah to Dubai."
  );
  const phoneHref = formatPhoneHref(BUSINESS.phone);

  const schemas = [
    localBusinessSchema(),
    serviceSchema({
      name: "Ladies Car Lift Sharjah to Dubai",
      description:
        "Ladies-only car lift from Sharjah to Dubai. Verified female drivers, ladies-only vehicles, GPS-tracked. From AED 300/month. Salik included.",
      url: "/ladies-car-lift-sharjah-to-dubai",
      price: "300",
    }),
    faqSchema(PAGE_FAQS),
    breadcrumbSchema([
      { name: "Home", url: "/" },
      { name: "Ladies Car Lift Sharjah to Dubai", url: "/ladies-car-lift-sharjah-to-dubai" },
    ]),
    primaryImageOfPageSchema({
      imageUrl: "/images/services/ladies-car-lift-interior-uae.webp",
      pageUrl: "/ladies-car-lift-sharjah-to-dubai",
      caption: "Ladies-only car lift interior UAE – safe women-only shared ride Sharjah to Dubai",
    }),
  ];

  return (
    <>
      <SchemaScript schema={schemas} />

      {/* ── Hero ─────────────────────────────────────────────────────────── */}
      <section
        aria-labelledby="hero-heading"
        className="relative overflow-hidden py-16 sm:py-20"
        style={{ background: "linear-gradient(135deg, #831843 0%, #be185d 50%, #500724 100%)" }}
      >
        <div
          className="absolute inset-0 opacity-[0.04] pointer-events-none"
          style={{ backgroundImage: "radial-gradient(circle, rgba(255,255,255,0.8) 1px, transparent 1px)", backgroundSize: "28px 28px" }}
          aria-hidden="true"
        />
        <div className="relative z-10 max-w-5xl mx-auto px-4 sm:px-6 lg:px-8">
          <Breadcrumb
            items={[{ label: "Home", href: "/" }, { label: "Ladies Car Lift Sharjah to Dubai" }]}
            className="mb-6 [&_*]:text-pink-400 [&_a]:text-pink-300 [&_a:hover]:text-white"
          />
          <div className="flex flex-col lg:flex-row lg:items-start lg:justify-between gap-10">
            <div className="flex-1">
              <div className="inline-flex items-center gap-2 bg-pink-500/20 border border-pink-400/30 rounded-full px-4 py-1.5 text-sm text-pink-200 font-semibold mb-5">
                <Shield className="h-4 w-4" aria-hidden="true" />
                Ladies Only · Female Driver Option · AED 300/Month
              </div>
              <h1 id="hero-heading" className="text-3xl sm:text-4xl lg:text-5xl font-extrabold text-white tracking-tight leading-tight mb-4">
                Ladies Car Lift<br className="hidden sm:block" /> Sharjah to Dubai
              </h1>
              <p className="text-pink-100 text-base sm:text-lg leading-relaxed mb-3 max-w-xl">
                A safe, comfortable daily car lift exclusively for women commuting from Sharjah to Dubai.
                Choose a verified female driver, or a ladies-only vehicle — GPS-tracked, Salik included.
              </p>
              <p className="text-pink-200/80 text-sm leading-relaxed mb-6 max-w-xl">
                &ldquo;I was nervous about daily commuting, but Car Lift UAE&apos;s ladies service made it stress-free.
                Same friendly driver every day, always on time.&rdquo; — Fatima A., Al Nahda, Sharjah.
              </p>
              <ul className="grid grid-cols-2 sm:grid-cols-4 gap-3 mb-8" role="list" aria-label="Ladies service highlights">
                {[
                  { icon: Shield, label: "Female Driver", sub: "On Request" },
                  { icon: DollarSign, label: "From AED 300", sub: "/month" },
                  { icon: Car, label: "GPS Tracked", sub: "Real-Time" },
                  { icon: Users, label: "Ladies Only", sub: "All Passengers" },
                ].map(({ icon: Icon, label, sub }) => (
                  <li key={sub} className="bg-white/10 border border-white/15 rounded-xl p-4 text-center">
                    <Icon className="h-5 w-5 text-pink-300 mx-auto mb-1.5" aria-hidden="true" />
                    <p className="text-white font-extrabold text-base leading-none">{label}</p>
                    <p className="text-pink-200/70 text-xs mt-1">{sub}</p>
                  </li>
                ))}
              </ul>
              <div className="flex flex-col sm:flex-row gap-3">
                <Button asChild variant="whatsapp" size="lg">
                  <a href={whatsappHref} target="_blank" rel="noopener noreferrer" aria-label="Book ladies car lift from Sharjah via WhatsApp">
                    <MessageCircle className="h-5 w-5" aria-hidden="true" />
                    Book via WhatsApp
                  </a>
                </Button>
                <Button asChild size="lg" className="border-2 border-white/30 bg-white/10 text-white hover:bg-white/20">
                  <a href={phoneHref} aria-label="Call Car Lift UAE">
                    <Phone className="h-5 w-5" aria-hidden="true" />
                    Call {BUSINESS.phone}
                  </a>
                </Button>
              </div>
            </div>
            <aside className="lg:w-72 bg-white/10 border border-white/15 backdrop-blur-sm rounded-2xl p-6 shrink-0" aria-label="Safety features">
              <p className="text-white font-bold text-base mb-4 flex items-center gap-2">
                <Shield className="h-5 w-5 text-pink-400" aria-hidden="true" />
                Your Safety Comes First
              </p>
              <ul className="space-y-3" role="list">
                {[
                  "Verified female driver option",
                  "Ladies-only passengers",
                  "GPS tracked in real time",
                  "Share live location",
                  "In-vehicle camera",
                  "Emergency contact alerts",
                  "24/7 WhatsApp support",
                  "Salik tolls included",
                ].map((item) => (
                  <li key={item} className="flex items-center gap-2.5">
                    <CheckCircle className="h-4 w-4 text-pink-400 shrink-0" aria-hidden="true" />
                    <span className="text-pink-100 text-sm">{item}</span>
                  </li>
                ))}
              </ul>
            </aside>
          </div>
        </div>
      </section>

      {/* ── Safety Features ──────────────────────────────────────────────── */}
      <section aria-labelledby="safety-heading" className="py-14 sm:py-16 bg-white">
        <div className="max-w-5xl mx-auto px-4 sm:px-6 lg:px-8">
          <div className="text-center mb-10">
            <p className="text-pink-600 font-semibold text-sm uppercase tracking-widest mb-3">Safety First</p>
            <h2 id="safety-heading" className="text-2xl sm:text-3xl font-extrabold text-slate-900 tracking-tight mb-3">
              Built for Safe, Daily Commuting for Women
            </h2>
            <p className="text-slate-600 max-w-xl mx-auto text-sm">
              Every feature of our ladies car lift is designed with your safety and peace of mind as the top priority.
            </p>
          </div>
          <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 gap-5">
            {SAFETY_FEATURES.map((feature) => (
              <Card key={feature.title} className="border-pink-100 hover:border-pink-200 transition-colors">
                <CardContent className="p-5 pt-5">
                  <div className="flex items-start gap-3">
                    <div className="w-9 h-9 rounded-xl bg-pink-100 flex items-center justify-center shrink-0">
                      <Shield className="h-5 w-5 text-pink-600" aria-hidden="true" />
                    </div>
                    <div>
                      <p className="font-bold text-slate-900 text-sm mb-1">{feature.title}</p>
                      <p className="text-slate-500 text-xs leading-relaxed">{feature.desc}</p>
                    </div>
                  </div>
                </CardContent>
              </Card>
            ))}
          </div>
        </div>
      </section>

      {/* ── Destinations & Pricing ───────────────────────────────────────── */}
      <section aria-labelledby="destinations-heading" className="py-14 sm:py-16 bg-slate-50">
        <div className="max-w-5xl mx-auto px-4 sm:px-6 lg:px-8">
          <div className="text-center mb-10">
            <p className="text-pink-600 font-semibold text-sm uppercase tracking-widest mb-3">Routes &amp; Pricing</p>
            <h2 id="destinations-heading" className="text-2xl sm:text-3xl font-extrabold text-slate-900 tracking-tight mb-3">
              Ladies Car Lift Destinations from Sharjah
            </h2>
          </div>
          <div className="grid grid-cols-1 lg:grid-cols-2 gap-8">
            <div>
              <h3 className="text-base font-bold text-slate-900 mb-4 flex items-center gap-2">
                <MapPin className="h-5 w-5 text-pink-500" aria-hidden="true" />
                Dubai Destinations Covered
              </h3>
              <div className="border border-slate-200 rounded-2xl overflow-hidden">
                <table className="w-full text-sm" aria-label="Ladies car lift destinations and pricing">
                  <thead className="bg-slate-50 border-b border-slate-200">
                    <tr>
                      <th className="text-left px-4 py-3 font-semibold text-slate-700">Destination</th>
                      <th className="text-center px-4 py-3 font-semibold text-slate-700">Journey</th>
                      <th className="text-right px-4 py-3 font-semibold text-slate-700">From</th>
                    </tr>
                  </thead>
                  <tbody>
                    {DESTINATIONS.map((row, i) => (
                      <tr key={row.area} className={i % 2 === 0 ? "bg-white" : "bg-slate-50/50"}>
                        <td className="px-4 py-3 text-slate-800 font-medium">{row.area}</td>
                        <td className="px-4 py-3 text-center text-slate-500 text-xs">{row.time}</td>
                        <td className="px-4 py-3 text-right font-extrabold text-pink-600">{row.price}</td>
                      </tr>
                    ))}
                  </tbody>
                </table>
              </div>
              <p className="text-slate-500 text-xs mt-3">Prices from Al Nahda, Sharjah. Salik always included.</p>
            </div>
            <div>
              <h3 className="text-base font-bold text-slate-900 mb-4 flex items-center gap-2">
                <MapPin className="h-5 w-5 text-pink-500" aria-hidden="true" />
                Sharjah Pickup Areas
              </h3>
              <ul className="grid grid-cols-1 sm:grid-cols-2 gap-2 list-none" role="list">
                {PICKUP_AREAS.map((area) => (
                  <li key={area} className="flex items-center gap-2.5 bg-white border border-slate-200 rounded-xl px-3 py-2.5">
                    <CheckCircle className="h-4 w-4 text-pink-500 shrink-0" aria-hidden="true" />
                    <span className="text-slate-800 font-medium text-sm">{area}</span>
                  </li>
                ))}
              </ul>
              <p className="text-slate-500 text-xs mt-3 italic">Don&apos;t see your area? WhatsApp us — we cover all of Sharjah.</p>
              <div className="mt-4">
                <Button asChild variant="whatsapp" size="default" className="w-full">
                  <a href={whatsappHref} target="_blank" rel="noopener noreferrer">
                    <MessageCircle className="h-4 w-4" aria-hidden="true" />
                    WhatsApp to Confirm Your Area
                  </a>
                </Button>
              </div>
            </div>
          </div>
        </div>
      </section>

      {/* ── FAQ ─────────────────────────────────────────────────────────── */}
      <section aria-labelledby="faq-heading" className="py-14 sm:py-16 bg-white">
        <div className="max-w-3xl mx-auto px-4 sm:px-6 lg:px-8">
          <div className="text-center mb-10">
            <p className="text-pink-600 font-semibold text-sm uppercase tracking-widest mb-3">FAQs</p>
            <h2 id="faq-heading" className="text-2xl sm:text-3xl font-extrabold text-slate-900 tracking-tight mb-3">
              Ladies Car Lift Sharjah – Common Questions
            </h2>
          </div>
          <dl className="space-y-4">
            {PAGE_FAQS.map((faq, i) => (
              <details key={i} className="group border border-slate-200 rounded-2xl overflow-hidden bg-white">
                <summary className="flex items-center justify-between gap-4 cursor-pointer p-5 font-semibold text-slate-900 hover:bg-slate-50 transition-colors list-none [&::-webkit-details-marker]:hidden">
                  <dt className="text-left text-base">{faq.question}</dt>
                  <ChevronDown className="h-5 w-5 text-slate-400 shrink-0 transition-transform duration-300 group-open:rotate-180" aria-hidden="true" />
                </summary>
                <dd className="px-5 pb-5 text-slate-600 leading-relaxed text-sm border-t border-slate-100 pt-4">
                  {faq.answer}
                </dd>
              </details>
            ))}
          </dl>
        </div>
      </section>

      {/* ── Related pages ────────────────────────────────────────────────── */}
      <section aria-label="Related car lift pages" className="py-12 bg-slate-50">
        <div className="max-w-5xl mx-auto px-4 sm:px-6 lg:px-8">
          <h2 className="text-xl font-bold text-slate-900 mb-6 text-center">Related Car Lift Services</h2>
          <ul className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-4 gap-4 list-none" role="list">
            {[
              { href: "/car-lift-from-sharjah-to-business-bay", label: "Car Lift Sharjah to Business Bay", desc: "Full route guide & pricing" },
              { href: "/carlift-sharjah-to-dubai-business-bay", label: "Carlift Sharjah to Dubai", desc: "Dubai-wide routes & monthly plans" },
              { href: "/carlift-sharjah-to-difc", label: "Carlift Sharjah to DIFC", desc: "DIFC Gate 1 & Gate 4 drop-off" },
              { href: "/monthly-pick-and-drop-service-sharjah", label: "Monthly Pick & Drop", desc: "26-day monthly subscription" },
            ].map(({ href, label, desc }) => (
              <li key={href}>
                <Link href={href} className="group flex flex-col gap-2 p-5 border border-slate-200 hover:border-pink-300 rounded-2xl hover:shadow-md transition-all h-full">
                  <span className="font-bold text-slate-900 group-hover:text-pink-600 text-sm">{label}</span>
                  <span className="text-slate-500 text-xs flex-1">{desc}</span>
                  <span className="text-pink-500 text-xs font-medium flex items-center gap-1 mt-2">
                    Learn more <ArrowRight className="h-3 w-3" aria-hidden="true" />
                  </span>
                </Link>
              </li>
            ))}
          </ul>
        </div>
      </section>

      {/* ── Final CTA ────────────────────────────────────────────────────── */}
      <section aria-label="Book ladies car lift" className="py-14 bg-pink-700">
        <div className="max-w-xl mx-auto px-4 text-center">
          <div className="flex items-center justify-center gap-0.5 mb-3" role="img" aria-label="4.9 out of 5 stars">
            {Array.from({ length: 5 }).map((_, i) => (
              <Star key={i} className="h-5 w-5 fill-amber-400 text-amber-400" aria-hidden="true" />
            ))}
          </div>
          <h2 className="text-white font-extrabold text-2xl sm:text-3xl mb-3">
            Book Your Ladies Car Lift Today
          </h2>
          <p className="text-pink-100 text-sm mb-6">
            {BUSINESS.reviewCount}+ daily riders trust Car Lift UAE. Ladies seats fill fast — WhatsApp now to secure yours.
          </p>
          <div className="flex flex-col sm:flex-row gap-3 justify-center">
            <Button asChild size="xl" className="bg-white text-pink-700 hover:bg-pink-50 font-bold">
              <a href={whatsappHref} target="_blank" rel="noopener noreferrer" aria-label="Book ladies car lift from Sharjah">
                <MessageCircle className="h-5 w-5" aria-hidden="true" />
                WhatsApp – Book Now
              </a>
            </Button>
            <Button asChild size="xl" className="border-2 border-white/40 bg-white/10 text-white hover:bg-white/20">
              <a href={phoneHref}>
                <Phone className="h-5 w-5" aria-hidden="true" />
                Call {BUSINESS.phone}
              </a>
            </Button>
          </div>
        </div>
      </section>
    </>
  );
}
