import type { Metadata } from "next";
import Link from "next/link";
import {
  Car,
  Clock,
  DollarSign,
  MapPin,
  CheckCircle,
  MessageCircle,
  Phone,
  ArrowRight,
  ChevronDown,
  Users,
  Star,
  Shield,
  Calendar,
} from "lucide-react";
import { Card, CardContent } from "@/components/ui/card";
import { Button } from "@/components/ui/button";
import Breadcrumb from "@/components/sections/breadcrumb";
import SchemaScript from "@/components/sections/schema-script";
import {
  localBusinessSchema,
  faqSchema,
  breadcrumbSchema,
  serviceSchema,
  primaryImageOfPageSchema,
} from "@/lib/schema";
import { BUSINESS, formatWhatsAppHref, formatPhoneHref } from "@/lib/utils";

export const revalidate = 86400;

export const metadata: Metadata = {
  title: "Monthly Pick and Drop Service Sharjah to Dubai – AED 300/Month | +971 54 330 8261",
  description:
    "Monthly pick and drop service from Sharjah to Dubai from AED 300/month. GPS-tracked van, Salik included, verified driver, 4.9★ rated. Ladies option. WhatsApp +971 54 330 8261 now.",
  keywords:
    "monthly pick and drop service sharjah, monthly pick and drop service from sharjah to dubai, monthly pick and drop service in sharjah, pick and drop sharjah dubai monthly, monthly car lift sharjah",
  alternates: {
    canonical: "https://www.carliftuae.com/monthly-pick-and-drop-service-sharjah",
  },
  openGraph: {
    title: "Monthly Pick and Drop Service Sharjah to Dubai – AED 300/Month | +971 54 330 8261",
    description:
      "Monthly pick and drop from Sharjah to Dubai from AED 300/month. 26 working days, morning + evening. Salik included. Ladies option. WhatsApp +971 54 330 8261.",
    // OG image generated by src/app/monthly-pick-and-drop-service-sharjah/opengraph-image.tsx
  },
};

const PAGE_FAQS = [
  {
    question: "What is a monthly pick and drop service from Sharjah to Dubai?",
    answer:
      "A monthly pick and drop service is a fixed subscription where a GPS-tracked vehicle picks you up from your Sharjah building every morning and drops you at your Dubai office, then brings you back in the evening — 26 working days/month, same timing, same seat. No daily booking, no app juggling, no surge pricing.",
  },
  {
    question: "How much does the monthly pick and drop service from Sharjah cost?",
    answer:
      "Monthly pick and drop from Sharjah to Dubai Business Bay starts at AED 300/month from Al Nahda, Sharjah. Al Taawun and Al Khan are AED 320. Muweilah and farther areas are AED 350–420/month. Salik tolls, morning and evening rides are all included. No hidden charges.",
  },
  {
    question: "What does the monthly package include?",
    answer:
      "Your monthly package includes 26 working days (Monday to Saturday), morning pickup and evening drop-off, Salik toll coverage for all gates, a GPS-tracked air-conditioned vehicle, a verified UAE-licensed driver, and WhatsApp support 24/7. You can also request a ladies-only vehicle at no extra cost.",
  },
  {
    question: "What are the pick-up timings for the morning service?",
    answer:
      "Morning departures from Sharjah: 6:30 AM, 7:00 AM, 7:30 AM, and 8:00 AM. Evening return from Dubai: 5:00 PM, 5:30 PM, 6:00 PM, and 6:30 PM. You choose your preferred slot when you book and keep it for the full month.",
  },
  {
    question: "Which Sharjah areas are covered for pick and drop?",
    answer:
      "We cover Al Nahda, Muweilah, Al Taawun, Al Khan, Al Majaz, Al Qusais, University City, Al Zahia, Rolla, Al Qasimia, and more. WhatsApp your building name and we will confirm your nearest pickup point within minutes.",
  },
  {
    question: "Is there a ladies-only monthly pick and drop from Sharjah?",
    answer:
      "Yes. We offer a dedicated ladies-only monthly service from Sharjah to Dubai with a female driver available on request. The vehicle carries female passengers only, so it is a safe and comfortable option for women commuting daily to Dubai.",
  },
];

const TIMINGS = [
  { label: "Sharjah → Dubai (Morning)", times: ["6:30 AM", "7:00 AM", "7:30 AM", "8:00 AM"], color: "bg-emerald-600" },
  { label: "Dubai → Sharjah (Evening)", times: ["5:00 PM", "5:30 PM", "6:00 PM", "6:30 PM"], color: "bg-slate-800" },
];

const PICKUP_AREAS = [
  "Al Nahda (Sharjah)", "Muweilah", "Al Taawun", "Al Khan",
  "Al Majaz", "Al Qusais", "University City", "Al Zahia",
  "Rolla Area", "Al Qasimia",
];

const PRICING_AREAS = [
  { area: "Al Nahda", price: "AED 300", note: "Closest to Dubai" },
  { area: "Al Taawun / Al Khan", price: "AED 320", note: "" },
  { area: "Al Majaz / Rolla", price: "AED 350", note: "" },
  { area: "Muweilah", price: "AED 380", note: "" },
  { area: "University City / Al Zahia", price: "AED 420", note: "Farther zone" },
];

const COST_COMPARISON = [
  { item: "Fuel (Sharjah → Dubai daily)", driving: "AED 480", carlift: "—" },
  { item: "Salik tolls", driving: "AED 312", carlift: "Included" },
  { item: "Parking in Business Bay", driving: "AED 660", carlift: "—" },
  { item: "Total monthly cost", driving: "AED 1,452", carlift: "AED 300", highlight: true },
];

export default function MonthlyPickAndDropServiceSharjahPage() {
  const whatsappHref = formatWhatsAppHref(
    BUSINESS.whatsapp,
    "Hi! I want to book monthly pick and drop service from Sharjah to Dubai."
  );
  const phoneHref = formatPhoneHref(BUSINESS.phone);

  const schemas = [
    localBusinessSchema(),
    serviceSchema({
      name: "Monthly Pick and Drop Service Sharjah to Dubai",
      description:
        "Monthly pick and drop service from Sharjah to Dubai. 26 working days, morning + evening rides. Salik included. From AED 300/month.",
      url: "/monthly-pick-and-drop-service-sharjah",
      price: "300",
    }),
    faqSchema(PAGE_FAQS),
    breadcrumbSchema([
      { name: "Home", url: "/" },
      { name: "Monthly Pick and Drop Service Sharjah", url: "/monthly-pick-and-drop-service-sharjah" },
    ]),
    primaryImageOfPageSchema({
      imageUrl: "/images/locations/sharjah/sharjah-car-lift-morning-pickup.webp",
      pageUrl: "/monthly-pick-and-drop-service-sharjah",
      caption: "Monthly pick and drop service Sharjah to Dubai – Car Lift UAE morning pickup",
    }),
  ];

  return (
    <>
      <SchemaScript schema={schemas} />

      {/* ── Hero ─────────────────────────────────────────────────────────── */}
      <section
        aria-labelledby="hero-heading"
        className="relative overflow-hidden py-16 sm:py-20"
        style={{ background: "linear-gradient(135deg, #064e3b 0%, #065f46 50%, #022c22 100%)" }}
      >
        <div
          className="absolute inset-0 opacity-[0.04] pointer-events-none"
          style={{ backgroundImage: "radial-gradient(circle, rgba(255,255,255,0.8) 1px, transparent 1px)", backgroundSize: "28px 28px" }}
          aria-hidden="true"
        />
        <div className="relative z-10 max-w-5xl mx-auto px-4 sm:px-6 lg:px-8">
          <Breadcrumb
            items={[{ label: "Home", href: "/" }, { label: "Monthly Pick and Drop Service Sharjah" }]}
            className="mb-6 [&_*]:text-emerald-400 [&_a]:text-emerald-300 [&_a:hover]:text-white"
          />
          <div className="flex flex-col lg:flex-row lg:items-start lg:justify-between gap-10">
            <div className="flex-1">
              <div className="inline-flex items-center gap-2 bg-emerald-500/20 border border-emerald-400/30 rounded-full px-4 py-1.5 text-sm text-emerald-300 font-semibold mb-5">
                <Calendar className="h-4 w-4" aria-hidden="true" />
                AED 300/Month · 26 Days · Salik Included
              </div>
              <h1 id="hero-heading" className="text-3xl sm:text-4xl lg:text-5xl font-extrabold text-white tracking-tight leading-tight mb-4">
                Monthly Pick &amp; Drop Service<br className="hidden sm:block" /> Sharjah to Dubai
              </h1>
              <p className="text-emerald-100 text-base sm:text-lg leading-relaxed mb-3 max-w-xl">
                Tired of paying AED 1,200+/month driving yourself to Dubai? Switch to a monthly pick and drop
                subscription from AED 300/month — morning pickup, evening return, Salik included, zero hassle.
              </p>
              <p className="text-emerald-200/80 text-sm leading-relaxed mb-6 max-w-xl">
                GPS-tracked vehicle, verified UAE driver, air-conditioned — same seat, same time, every single working day.
              </p>
              <ul className="grid grid-cols-2 sm:grid-cols-4 gap-3 mb-8" role="list" aria-label="Monthly service highlights">
                {[
                  { icon: DollarSign, label: "From AED 300", sub: "/month" },
                  { icon: Calendar, label: "26 Days", sub: "Working Days" },
                  { icon: Clock, label: "4 Timings", sub: "Morning Slots" },
                  { icon: Users, label: "Both Ways", sub: "AM + PM" },
                ].map(({ icon: Icon, label, sub }) => (
                  <li key={sub} className="bg-white/10 border border-white/15 rounded-xl p-4 text-center">
                    <Icon className="h-5 w-5 text-emerald-400 mx-auto mb-1.5" aria-hidden="true" />
                    <p className="text-white font-extrabold text-base leading-none">{label}</p>
                    <p className="text-emerald-200/70 text-xs mt-1">{sub}</p>
                  </li>
                ))}
              </ul>
              <div className="flex flex-col sm:flex-row gap-3">
                <Button asChild variant="whatsapp" size="lg">
                  <a href={whatsappHref} target="_blank" rel="noopener noreferrer" aria-label="Book monthly pick and drop from Sharjah via WhatsApp">
                    <MessageCircle className="h-5 w-5" aria-hidden="true" />
                    Book via WhatsApp
                  </a>
                </Button>
                <Button asChild size="lg" className="border-2 border-white/30 bg-white/10 text-white hover:bg-white/20">
                  <a href={phoneHref} aria-label="Call Car Lift UAE">
                    <Phone className="h-5 w-5" aria-hidden="true" />
                    Call {BUSINESS.phone}
                  </a>
                </Button>
              </div>
            </div>
            <aside className="lg:w-72 bg-white/10 border border-white/15 backdrop-blur-sm rounded-2xl p-6 shrink-0" aria-label="What is included">
              <p className="text-white font-bold text-base mb-4 flex items-center gap-2">
                <CheckCircle className="h-5 w-5 text-emerald-400" aria-hidden="true" />
                What&apos;s Included
              </p>
              <ul className="space-y-3" role="list">
                {[
                  "Morning & evening rides",
                  "26 working days/month",
                  "Salik tolls included",
                  "GPS-tracked vehicle",
                  "Verified UAE driver",
                  "Air-conditioned vehicle",
                  "WhatsApp support 24/7",
                  "Ladies-only option",
                ].map((item) => (
                  <li key={item} className="flex items-center gap-2.5">
                    <CheckCircle className="h-4 w-4 text-emerald-400 shrink-0" aria-hidden="true" />
                    <span className="text-emerald-100 text-sm">{item}</span>
                  </li>
                ))}
              </ul>
            </aside>
          </div>
        </div>
      </section>

      {/* ── Cost Comparison ──────────────────────────────────────────────── */}
      <section aria-labelledby="comparison-heading" className="py-14 sm:py-16 bg-white">
        <div className="max-w-5xl mx-auto px-4 sm:px-6 lg:px-8">
          <div className="text-center mb-10">
            <p className="text-emerald-600 font-semibold text-sm uppercase tracking-widest mb-3">Real Numbers</p>
            <h2 id="comparison-heading" className="text-2xl sm:text-3xl font-extrabold text-slate-900 tracking-tight mb-3">
              Driving Yourself vs. Monthly Pick &amp; Drop
            </h2>
            <p className="text-slate-600 max-w-xl mx-auto text-sm">
              Most Sharjah residents spend over AED 1,400/month commuting to Dubai when you add fuel, Salik, and parking. Here is what you actually pay:
            </p>
          </div>
          <div className="border border-slate-200 rounded-2xl overflow-hidden max-w-2xl mx-auto mb-8">
            <table className="w-full text-sm" aria-label="Cost comparison driving vs car lift">
              <thead className="bg-slate-50 border-b border-slate-200">
                <tr>
                  <th className="text-left px-4 py-3 font-semibold text-slate-700">Monthly Cost</th>
                  <th className="text-right px-4 py-3 font-semibold text-red-600">Driving Yourself</th>
                  <th className="text-right px-4 py-3 font-semibold text-emerald-600">Car Lift UAE</th>
                </tr>
              </thead>
              <tbody>
                {COST_COMPARISON.map((row, i) => (
                  <tr key={row.item} className={row.highlight ? "bg-emerald-50 font-bold border-t-2 border-emerald-200" : i % 2 === 0 ? "bg-white" : "bg-slate-50/50"}>
                    <td className="px-4 py-3 text-slate-800">{row.item}</td>
                    <td className="px-4 py-3 text-right text-red-600">{row.driving}</td>
                    <td className="px-4 py-3 text-right text-emerald-600">{row.carlift}</td>
                  </tr>
                ))}
              </tbody>
            </table>
          </div>
          <div className="text-center">
            <p className="text-slate-500 text-sm mb-4">That is a saving of over <strong className="text-emerald-600">AED 1,150/month</strong> — AED 13,800/year.</p>
            <Button asChild variant="whatsapp" size="default">
              <a href={whatsappHref} target="_blank" rel="noopener noreferrer">
                <MessageCircle className="h-4 w-4" aria-hidden="true" />
                Start Saving – WhatsApp Now
              </a>
            </Button>
          </div>
        </div>
      </section>

      {/* ── Timings ─────────────────────────────────────────────────────── */}
      <section aria-labelledby="timings-heading" className="py-14 sm:py-16 bg-slate-50">
        <div className="max-w-5xl mx-auto px-4 sm:px-6 lg:px-8">
          <div className="text-center mb-10">
            <p className="text-emerald-600 font-semibold text-sm uppercase tracking-widest mb-3">Daily Schedule</p>
            <h2 id="timings-heading" className="text-2xl sm:text-3xl font-extrabold text-slate-900 tracking-tight mb-3">
              Pick &amp; Drop Timings – Sharjah to Dubai
            </h2>
            <p className="text-slate-600 max-w-xl mx-auto text-sm">
              Fixed departures Monday to Saturday. Your seat is reserved for the same slot every day.
            </p>
          </div>
          <div className="grid grid-cols-1 sm:grid-cols-2 gap-6 mb-6">
            {TIMINGS.map((t) => (
              <Card key={t.label} className="border-slate-200">
                <CardContent className="p-6 pt-6">
                  <div className="flex items-center gap-3 mb-5">
                    <div className={`w-9 h-9 rounded-xl ${t.color} flex items-center justify-center shrink-0`}>
                      <Clock className="h-5 w-5 text-white" aria-hidden="true" />
                    </div>
                    <h3 className="font-bold text-slate-900 text-sm">{t.label}</h3>
                  </div>
                  <div className="grid grid-cols-2 gap-3">
                    {t.times.map((time) => (
                      <div key={time} className="bg-slate-50 border border-slate-200 rounded-xl p-3 text-center">
                        <p className="font-extrabold text-slate-900 text-xl">{time}</p>
                      </div>
                    ))}
                  </div>
                </CardContent>
              </Card>
            ))}
          </div>
        </div>
      </section>

      {/* ── Pickup Areas & Pricing ───────────────────────────────────────── */}
      <section aria-labelledby="pricing-heading" className="py-14 sm:py-16 bg-white">
        <div className="max-w-5xl mx-auto px-4 sm:px-6 lg:px-8">
          <div className="text-center mb-10">
            <p className="text-emerald-600 font-semibold text-sm uppercase tracking-widest mb-3">Transparent Pricing</p>
            <h2 id="pricing-heading" className="text-2xl sm:text-3xl font-extrabold text-slate-900 tracking-tight mb-3">
              Monthly Package Pricing by Sharjah Area
            </h2>
          </div>
          <div className="grid grid-cols-1 lg:grid-cols-2 gap-8 items-start">
            <div>
              <h3 className="text-base font-bold text-slate-900 mb-4 flex items-center gap-2">
                <MapPin className="h-5 w-5 text-emerald-500" aria-hidden="true" />
                Pickup Areas &amp; Monthly Rates
              </h3>
              <div className="border border-slate-200 rounded-2xl overflow-hidden mb-4">
                <table className="w-full text-sm" aria-label="Pick and drop pricing by Sharjah area">
                  <thead className="bg-slate-50 border-b border-slate-200">
                    <tr>
                      <th className="text-left px-4 py-3 font-semibold text-slate-700">Pickup Area (Sharjah)</th>
                      <th className="text-right px-4 py-3 font-semibold text-slate-700">Monthly Price</th>
                    </tr>
                  </thead>
                  <tbody>
                    {PRICING_AREAS.map((row, i) => (
                      <tr key={row.area} className={i % 2 === 0 ? "bg-white" : "bg-slate-50/50"}>
                        <td className="px-4 py-3 text-slate-800 font-medium">
                          {row.area}
                          {row.note && <span className="ml-2 text-xs text-slate-400">({row.note})</span>}
                        </td>
                        <td className="px-4 py-3 text-right font-extrabold text-emerald-600">{row.price}</td>
                      </tr>
                    ))}
                  </tbody>
                </table>
              </div>
              <p className="text-slate-500 text-xs">All prices include Salik, morning and evening rides, 6 days/week.</p>
            </div>
            <div className="space-y-4">
              <div>
                <h3 className="text-base font-bold text-slate-900 mb-3 flex items-center gap-2">
                  <MapPin className="h-5 w-5 text-blue-500" aria-hidden="true" />
                  All Sharjah Pickup Points
                </h3>
                <ul className="grid grid-cols-1 sm:grid-cols-2 gap-2 list-none" role="list">
                  {PICKUP_AREAS.map((area) => (
                    <li key={area} className="flex items-center gap-2.5 bg-slate-50 border border-slate-200 rounded-xl px-3 py-2.5">
                      <CheckCircle className="h-4 w-4 text-emerald-500 shrink-0" aria-hidden="true" />
                      <span className="text-slate-800 font-medium text-sm">{area}</span>
                    </li>
                  ))}
                </ul>
                <p className="text-slate-500 text-xs mt-2 italic">Don&apos;t see your area? WhatsApp us — we cover all of Sharjah.</p>
              </div>
              <Card className="border-emerald-200 bg-emerald-50">
                <CardContent className="p-5 pt-5">
                  <div className="flex items-start gap-3">
                    <div className="w-10 h-10 rounded-full bg-emerald-500 flex items-center justify-center shrink-0">
                      <Shield className="h-5 w-5 text-white" aria-hidden="true" />
                    </div>
                    <div>
                      <p className="font-bold text-emerald-900 text-sm mb-1">No Hidden Charges — Ever</p>
                      <p className="text-emerald-700 text-xs leading-relaxed">
                        The price you see is the price you pay. Payment via cash, bank transfer, or WhatsApp Pay at the start of each month.
                      </p>
                    </div>
                  </div>
                </CardContent>
              </Card>
              <Button asChild variant="whatsapp" size="lg" className="w-full">
                <a href={whatsappHref} target="_blank" rel="noopener noreferrer">
                  <MessageCircle className="h-5 w-5" aria-hidden="true" />
                  Get Your Exact Price via WhatsApp
                </a>
              </Button>
            </div>
          </div>
        </div>
      </section>

      {/* ── FAQ ─────────────────────────────────────────────────────────── */}
      <section aria-labelledby="faq-heading" className="py-14 sm:py-16 bg-slate-50">
        <div className="max-w-3xl mx-auto px-4 sm:px-6 lg:px-8">
          <div className="text-center mb-10">
            <p className="text-emerald-600 font-semibold text-sm uppercase tracking-widest mb-3">FAQs</p>
            <h2 id="faq-heading" className="text-2xl sm:text-3xl font-extrabold text-slate-900 tracking-tight mb-3">
              Monthly Pick &amp; Drop Service – Common Questions
            </h2>
          </div>
          <dl className="space-y-4">
            {PAGE_FAQS.map((faq, i) => (
              <details key={i} className="group border border-slate-200 rounded-2xl overflow-hidden bg-white">
                <summary className="flex items-center justify-between gap-4 cursor-pointer p-5 font-semibold text-slate-900 hover:bg-slate-50 transition-colors list-none [&::-webkit-details-marker]:hidden">
                  <dt className="text-left text-base">{faq.question}</dt>
                  <ChevronDown className="h-5 w-5 text-slate-400 shrink-0 transition-transform duration-300 group-open:rotate-180" aria-hidden="true" />
                </summary>
                <dd className="px-5 pb-5 text-slate-600 leading-relaxed text-sm border-t border-slate-100 pt-4">
                  {faq.answer}
                </dd>
              </details>
            ))}
          </dl>
          <div className="mt-8 text-center">
            <Button asChild variant="outline" size="default">
              <a href={whatsappHref} target="_blank" rel="noopener noreferrer">
                <MessageCircle className="h-4 w-4" aria-hidden="true" />
                Ask on WhatsApp
              </a>
            </Button>
          </div>
        </div>
      </section>

      {/* ── Related pages ────────────────────────────────────────────────── */}
      <section aria-label="Related car lift pages" className="py-12 bg-white">
        <div className="max-w-5xl mx-auto px-4 sm:px-6 lg:px-8">
          <h2 className="text-xl font-bold text-slate-900 mb-6 text-center">Related Car Lift Services</h2>
          <ul className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-4 gap-4 list-none" role="list">
            {[
              { href: "/car-lift-from-sharjah-to-business-bay", label: "Car Lift Sharjah to Business Bay", desc: "Full route guide, pricing & timings" },
              { href: "/carlift-sharjah-to-dubai-business-bay", label: "Carlift Sharjah to Dubai", desc: "Dubai-wide routes & monthly pricing" },
              { href: "/ladies-car-lift-sharjah-to-dubai", label: "Ladies Car Lift Sharjah", desc: "Female driver option, ladies-only" },
              { href: "/routes", label: "All Car Lift Routes", desc: "Browse all Sharjah & Ajman routes" },
            ].map(({ href, label, desc }) => (
              <li key={href}>
                <Link href={href} className="group flex flex-col gap-2 p-5 border border-slate-200 hover:border-emerald-300 rounded-2xl hover:shadow-md transition-all h-full">
                  <span className="font-bold text-slate-900 group-hover:text-emerald-600 text-sm">{label}</span>
                  <span className="text-slate-500 text-xs flex-1">{desc}</span>
                  <span className="text-emerald-500 text-xs font-medium flex items-center gap-1 mt-2">
                    Learn more <ArrowRight className="h-3 w-3" aria-hidden="true" />
                  </span>
                </Link>
              </li>
            ))}
          </ul>
        </div>
      </section>

      {/* ── Final CTA ────────────────────────────────────────────────────── */}
      <section aria-label="Book your monthly pick and drop" className="py-14 bg-emerald-600">
        <div className="max-w-xl mx-auto px-4 text-center">
          <div className="flex items-center justify-center gap-0.5 mb-3" role="img" aria-label="4.9 out of 5 stars">
            {Array.from({ length: 5 }).map((_, i) => (
              <Star key={i} className="h-5 w-5 fill-amber-400 text-amber-400" aria-hidden="true" />
            ))}
          </div>
          <h2 className="text-white font-extrabold text-2xl sm:text-3xl mb-3">
            Book Your Monthly Pick &amp; Drop Today
          </h2>
          <p className="text-emerald-100 text-sm mb-6">
            {BUSINESS.reviewCount}+ daily riders trust Car Lift UAE. Monthly seats fill fast — WhatsApp now to secure yours.
          </p>
          <div className="flex flex-col sm:flex-row gap-3 justify-center">
            <Button asChild size="xl" className="bg-white text-emerald-700 hover:bg-emerald-50 font-bold">
              <a href={whatsappHref} target="_blank" rel="noopener noreferrer" aria-label="Book monthly pick and drop from Sharjah">
                <MessageCircle className="h-5 w-5" aria-hidden="true" />
                WhatsApp – Book Now
              </a>
            </Button>
            <Button asChild size="xl" className="border-2 border-white/40 bg-white/10 text-white hover:bg-white/20">
              <a href={phoneHref}>
                <Phone className="h-5 w-5" aria-hidden="true" />
                Call {BUSINESS.phone}
              </a>
            </Button>
          </div>
        </div>
      </section>
    </>
  );
}
